package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA

import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * InstitucionesEducativas generated by hbm2java
 */
public class InstitucionesEducativas implements java.io.Serializable {

    private int id;
    private String descripcion;
    private String direccion;
    private String numeroDireccion;
    private String casillaPostal;
    private String url;
    private String email;
    private int ubicacionId;
    private String tipo;
    private String nivel;
    private byte categoria;
    private String estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private Integer catinsId;
    private Integer tipinsId;
    private Set titulosProfesionaleses = new HashSet(0);
    boolean seleccionado = false;
    String campo = "Descripcion";

    public InstitucionesEducativas() {
    }

    public InstitucionesEducativas(int id, String descripcion, int ubicacionId, String tipo, String nivel, byte categoria) {
        this.id = id;
        this.descripcion = descripcion;
        this.ubicacionId = ubicacionId;
        this.tipo = tipo;
        this.nivel = nivel;
        this.categoria = categoria;
    }

    public InstitucionesEducativas(int id, String descripcion, String direccion, String numeroDireccion, String casillaPostal, String url, String email, int ubicacionId, String tipo, String nivel, byte categoria, String estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Integer catinsId, Integer tipinsId, Set titulosProfesionaleses) {
        this.id = id;
        this.descripcion = descripcion;
        this.direccion = direccion;
        this.numeroDireccion = numeroDireccion;
        this.casillaPostal = casillaPostal;
        this.url = url;
        this.email = email;
        this.ubicacionId = ubicacionId;
        this.tipo = tipo;
        this.nivel = nivel;
        this.categoria = categoria;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.catinsId = catinsId;
        this.tipinsId = tipinsId;
        this.titulosProfesionaleses = titulosProfesionaleses;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getDireccion() {
        return this.direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    public String getNumeroDireccion() {
        return this.numeroDireccion;
    }

    public void setNumeroDireccion(String numeroDireccion) {
        this.numeroDireccion = numeroDireccion;
    }

    public String getCasillaPostal() {
        return this.casillaPostal;
    }

    public void setCasillaPostal(String casillaPostal) {
        this.casillaPostal = casillaPostal;
    }

    public String getUrl() {
        return this.url;
    }

    public void setUrl(String url) {
        this.url = url;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public int getUbicacionId() {
        return this.ubicacionId;
    }

    public void setUbicacionId(int ubicacionId) {
        this.ubicacionId = ubicacionId;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getNivel() {
        return this.nivel;
    }

    public void setNivel(String nivel) {
        this.nivel = nivel;
    }

    public byte getCategoria() {
        return this.categoria;
    }

    public void setCategoria(byte categoria) {
        this.categoria = categoria;
    }

    public String getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(String estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Integer getCatinsId() {
        return this.catinsId;
    }

    public void setCatinsId(Integer catinsId) {
        this.catinsId = catinsId;
    }

    public Integer getTipinsId() {
        return this.tipinsId;
    }

    public void setTipinsId(Integer tipinsId) {
        this.tipinsId = tipinsId;
    }

    public Set getTitulosProfesionaleses() {
        return titulosProfesionaleses;
    }

    public void setTitulosProfesionaleses(Set titulosProfesionaleses) {
        this.titulosProfesionaleses = titulosProfesionaleses;
    }

    public String getCampo() throws NoSuchMethodException, IllegalAccessException, IllegalArgumentException, InvocationTargetException {

        Method getDescripcion = this.getClass().getMethod("get" + campo, new Class[0]);
        String descripcion = (String) getDescripcion.invoke(this, new Object[0]);

        return descripcion;
    }

    public void setCampo(String campo) {
        this.campo = campo;
    }

    public boolean isSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }
}
