package datos.pojos.adminuc;
// Generated 24/08/2011 09:18:12 AM by Hibernate Tools 3.2.1.GA



/**
 * ListaEntidadesId generated by hbm2java
 */
public class ListaEntidadesId  implements java.io.Serializable {


     private int id;
     private int lisdisId;

    public ListaEntidadesId() {
    }

    public ListaEntidadesId(int id, int lisdisId) {
       this.id = id;
       this.lisdisId = lisdisId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getLisdisId() {
        return this.lisdisId;
    }
    
    public void setLisdisId(int lisdisId) {
        this.lisdisId = lisdisId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ListaEntidadesId) ) return false;
		 ListaEntidadesId castOther = ( ListaEntidadesId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getLisdisId()==castOther.getLisdisId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getLisdisId();
         return result;
   }   


}


