package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA



/**
 * MenusRolesId generated by hbm2java
 */
public class MenusRolesId  implements java.io.Serializable {


     private String rolId;
     private int menuId;

    public MenusRolesId() {
    }

    public MenusRolesId(String rolId, int menuId) {
       this.rolId = rolId;
       this.menuId = menuId;
    }
   
    public String getRolId() {
        return this.rolId;
    }
    
    public void setRolId(String rolId) {
        this.rolId = rolId;
    }
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MenusRolesId) ) return false;
		 MenusRolesId castOther = ( MenusRolesId ) other; 
         
		 return ( (this.getRolId()==castOther.getRolId()) || ( this.getRolId()!=null && castOther.getRolId()!=null && this.getRolId().equals(castOther.getRolId()) ) )
 && (this.getMenuId()==castOther.getMenuId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getRolId() == null ? 0 : this.getRolId().hashCode() );
         result = 37 * result + this.getMenuId();
         return result;
   }   


}


