package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * NivelesFormacion generated by hbm2java
 */
public class NivelesFormacion  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String nivel;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set titulosProfesionaleses = new HashSet(0);
     private Set tituloses = new HashSet(0);

    public NivelesFormacion() {
    }

    public NivelesFormacion(int id) {
        this.id = id;
    }

	
    public NivelesFormacion(int id, String nombre, String nivel, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.nivel = nivel;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public NivelesFormacion(int id, String nombre, String nivel, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set titulosProfesionaleses, Set tituloses) {
       this.id = id;
       this.nombre = nombre;
       this.nivel = nivel;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.titulosProfesionaleses = titulosProfesionaleses;
       this.tituloses = tituloses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNivel() {
        return this.nivel;
    }
    
    public void setNivel(String nivel) {
        this.nivel = nivel;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getTituloses() {
        return this.tituloses;
    }
    
    public void setTituloses(Set tituloses) {
        this.tituloses = tituloses;
    }

    public Set getTitulosProfesionaleses() {
        return titulosProfesionaleses;
    }

    public void setTitulosProfesionaleses(Set titulosProfesionaleses) {
        this.titulosProfesionaleses = titulosProfesionaleses;
    }




}


