package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA



/**
 * PermisosMenusId generated by hbm2java
 */
public class PermisosMenusId  implements java.io.Serializable {


     private String usuariPersonid;
     private String rolId;
     private int menuId;

    public PermisosMenusId() {
    }

    public PermisosMenusId(String usuariPersonid, String rolId, int menuId) {
       this.usuariPersonid = usuariPersonid;
       this.rolId = rolId;
       this.menuId = menuId;
    }
   
    public String getUsuariPersonid() {
        return this.usuariPersonid;
    }
    
    public void setUsuariPersonid(String usuariPersonid) {
        this.usuariPersonid = usuariPersonid;
    }
    public String getRolId() {
        return this.rolId;
    }
    
    public void setRolId(String rolId) {
        this.rolId = rolId;
    }
    public int getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(int menuId) {
        this.menuId = menuId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof PermisosMenusId) ) return false;
		 PermisosMenusId castOther = ( PermisosMenusId ) other; 
         
		 return ( (this.getUsuariPersonid()==castOther.getUsuariPersonid()) || ( this.getUsuariPersonid()!=null && castOther.getUsuariPersonid()!=null && this.getUsuariPersonid().equals(castOther.getUsuariPersonid()) ) )
 && ( (this.getRolId()==castOther.getRolId()) || ( this.getRolId()!=null && castOther.getRolId()!=null && this.getRolId().equals(castOther.getRolId()) ) )
 && (this.getMenuId()==castOther.getMenuId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getUsuariPersonid() == null ? 0 : this.getUsuariPersonid().hashCode() );
         result = 37 * result + ( getRolId() == null ? 0 : this.getRolId().hashCode() );
         result = 37 * result + this.getMenuId();
         return result;
   }   


}


