package datos.pojos.adminuc;
// Generated 16/01/2012 05:31:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PrtDiscapacidadesFamiliares generated by hbm2java
 */
public class PrtDiscapacidadesFamiliares  implements java.io.Serializable {


     private int id;
     private PrtTiposDiscapacidad prtTiposDiscapacidad;
     private PrtParientesDiscapacitados prtParientesDiscapacitados;
     private String otraDiscapacidad;
     private short porcentajeDiscapacidad;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private boolean seleccionado;
     private boolean ver;

    public PrtDiscapacidadesFamiliares() {
    }

	
    public PrtDiscapacidadesFamiliares(int id, PrtTiposDiscapacidad prtTiposDiscapacidad, PrtParientesDiscapacitados prtParientesDiscapacitados, short porcentajeDiscapacidad, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.prtTiposDiscapacidad = prtTiposDiscapacidad;
        this.prtParientesDiscapacitados = prtParientesDiscapacitados;
        this.porcentajeDiscapacidad = porcentajeDiscapacidad;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public PrtDiscapacidadesFamiliares(int id, PrtTiposDiscapacidad prtTiposDiscapacidad, PrtParientesDiscapacitados prtParientesDiscapacitados, String otraDiscapacidad, short porcentajeDiscapacidad, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.prtTiposDiscapacidad = prtTiposDiscapacidad;
       this.prtParientesDiscapacitados = prtParientesDiscapacitados;
       this.otraDiscapacidad = otraDiscapacidad;
       this.porcentajeDiscapacidad = porcentajeDiscapacidad;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public PrtTiposDiscapacidad getPrtTiposDiscapacidad() {
        return this.prtTiposDiscapacidad;
    }
    
    public void setPrtTiposDiscapacidad(PrtTiposDiscapacidad prtTiposDiscapacidad) {
        this.prtTiposDiscapacidad = prtTiposDiscapacidad;
    }
    public PrtParientesDiscapacitados getPrtParientesDiscapacitados() {
        return this.prtParientesDiscapacitados;
    }
    
    public void setPrtParientesDiscapacitados(PrtParientesDiscapacitados prtParientesDiscapacitados) {
        this.prtParientesDiscapacitados = prtParientesDiscapacitados;
    }
    public String getOtraDiscapacidad() {
        return this.otraDiscapacidad;
    }
    
    public void setOtraDiscapacidad(String otraDiscapacidad) {
        this.otraDiscapacidad = otraDiscapacidad;
    }
    public short getPorcentajeDiscapacidad() {
        return this.porcentajeDiscapacidad;
    }
    
    public void setPorcentajeDiscapacidad(short porcentajeDiscapacidad) {
        this.porcentajeDiscapacidad = porcentajeDiscapacidad;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public boolean isSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }

    public boolean isVer() {
        return ver;
    }

    public void setVer(boolean ver) {
        this.ver = ver;
    }




}


