package datos.pojos.adminuc;
// Generated 16/01/2012 05:31:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * PrtParentescos generated by hbm2java
 */
public class PrtParentescos  implements java.io.Serializable {


     private int id;
     private String nombre;
     private char aplicaEncuesta;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set<PrtParientesDiscapacitados> prtParientesDiscapacitadoses = new HashSet<PrtParientesDiscapacitados>(0);

    public PrtParentescos() {
    }

	
    public PrtParentescos(int id, String nombre, char aplicaEncuesta, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.aplicaEncuesta = aplicaEncuesta;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public PrtParentescos(int id, String nombre, char aplicaEncuesta, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set<PrtParientesDiscapacitados> prtParientesDiscapacitadoses) {
       this.id = id;
       this.nombre = nombre;
       this.aplicaEncuesta = aplicaEncuesta;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.prtParientesDiscapacitadoses = prtParientesDiscapacitadoses;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public char getAplicaEncuesta() {
        return this.aplicaEncuesta;
    }
    
    public void setAplicaEncuesta(char aplicaEncuesta) {
        this.aplicaEncuesta = aplicaEncuesta;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set<PrtParientesDiscapacitados> getPrtParientesDiscapacitadoses() {
        return this.prtParientesDiscapacitadoses;
    }
    
    public void setPrtParientesDiscapacitadoses(Set<PrtParientesDiscapacitados> prtParientesDiscapacitadoses) {
        this.prtParientesDiscapacitadoses = prtParientesDiscapacitadoses;
    }




}


