package datos.pojos.adminuc;
// Generated 16/01/2012 05:31:57 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * PrtPersonasDiscapacidades generated by hbm2java
 */
public class PrtPersonasDiscapacidades  implements java.io.Serializable {


     private int id;
     private PrtTiposDiscapacidad prtTiposDiscapacidad;
     private PrtDiscapacitados prtDiscapacitados;
     private String otraDiscapacidad;
     private short porcentajeDiscapacidad;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public PrtPersonasDiscapacidades() {
    }

	
    public PrtPersonasDiscapacidades(int id, PrtTiposDiscapacidad prtTiposDiscapacidad, PrtDiscapacitados prtDiscapacitados, short porcentajeDiscapacidad, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.prtTiposDiscapacidad = prtTiposDiscapacidad;
        this.prtDiscapacitados = prtDiscapacitados;
        this.porcentajeDiscapacidad = porcentajeDiscapacidad;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public PrtPersonasDiscapacidades(int id, PrtTiposDiscapacidad prtTiposDiscapacidad, PrtDiscapacitados prtDiscapacitados, String otraDiscapacidad, short porcentajeDiscapacidad, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.prtTiposDiscapacidad = prtTiposDiscapacidad;
       this.prtDiscapacitados = prtDiscapacitados;
       this.otraDiscapacidad = otraDiscapacidad;
       this.porcentajeDiscapacidad = porcentajeDiscapacidad;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public PrtTiposDiscapacidad getPrtTiposDiscapacidad() {
        return this.prtTiposDiscapacidad;
    }
    
    public void setPrtTiposDiscapacidad(PrtTiposDiscapacidad prtTiposDiscapacidad) {
        this.prtTiposDiscapacidad = prtTiposDiscapacidad;
    }
    public PrtDiscapacitados getPrtDiscapacitados() {
        return this.prtDiscapacitados;
    }
    
    public void setPrtDiscapacitados(PrtDiscapacitados prtDiscapacitados) {
        this.prtDiscapacitados = prtDiscapacitados;
    }
    public String getOtraDiscapacidad() {
        return this.otraDiscapacidad;
    }
    
    public void setOtraDiscapacidad(String otraDiscapacidad) {
        this.otraDiscapacidad = otraDiscapacidad;
    }
    public short getPorcentajeDiscapacidad() {
        return this.porcentajeDiscapacidad;
    }
    
    public void setPorcentajeDiscapacidad(short porcentajeDiscapacidad) {
        this.porcentajeDiscapacidad = porcentajeDiscapacidad;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


