package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpInstituciones generated by hbm2java
 */
public class SgpInstituciones  implements java.io.Serializable {


     private int id;
     private String ruc;
     private String nombre;
     private String direccion;
     private int ubicacionId;
     private String url;
     private String email;
     private char estaactivo;
     private String creado;
     private String fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpInstituciones() {
    }

	
    public SgpInstituciones(int id, String nombre, int ubicacionId, char estaactivo, String creado, String fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.ubicacionId = ubicacionId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpInstituciones(int id, String ruc, String nombre, String direccion, int ubicacionId, String url, String email, char estaactivo, String creado, String fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.ruc = ruc;
       this.nombre = nombre;
       this.direccion = direccion;
       this.ubicacionId = ubicacionId;
       this.url = url;
       this.email = email;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRuc() {
        return this.ruc;
    }
    
    public void setRuc(String ruc) {
        this.ruc = ruc;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public int getUbicacionId() {
        return this.ubicacionId;
    }
    
    public void setUbicacionId(int ubicacionId) {
        this.ubicacionId = ubicacionId;
    }
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public String getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(String fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


