package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.swing.tree.DefaultMutableTreeNode;
/**
 * Ubicaciones generated by hbm2java
 */
public class Ubicaciones implements java.io.Serializable {

    private int id;
    private String descripcion;
    private String abreviatura;
    private String nacionalidad;
    private String continente;
    private String regionGeo;
    private String escapital;
    private String tipo;
    private Long nivel;
    private int padre;
    private String codigoOficial;
    private String estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private String idZona;
    private String codigoSri;
    private Set titulosProfesionaleses = new HashSet(0);
    public DefaultMutableTreeNode Nodo;
     

    public Ubicaciones() {
    }

    public Ubicaciones(int id, String descripcion, String continente, String regionGeo, int padre, String estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.descripcion = descripcion;
        this.continente = continente;
        this.regionGeo = regionGeo;
        this.padre = padre;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public Ubicaciones(int id, String descripcion, String abreviatura, String nacionalidad, String continente, String regionGeo, String escapital, String tipo, Long nivel, int padre, String codigoOficial, String estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, String idZona, String codigoSri, Set titulosProfesionaleses) {
        this.id = id;
        this.descripcion = descripcion;
        this.abreviatura = abreviatura;
        this.nacionalidad = nacionalidad;
        this.continente = continente;
        this.regionGeo = regionGeo;
        this.escapital = escapital;
        this.tipo = tipo;
        this.nivel = nivel;
        this.padre = padre;
        this.codigoOficial = codigoOficial;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.idZona = idZona;
        this.codigoSri = codigoSri;
        this.titulosProfesionaleses = titulosProfesionaleses;

    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getDescripcion() {
        return this.descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public String getAbreviatura() {
        return this.abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public String getNacionalidad() {
        return this.nacionalidad;
    }

    public void setNacionalidad(String nacionalidad) {
        this.nacionalidad = nacionalidad;
    }

    public String getContinente() {
        return this.continente;
    }

    public void setContinente(String continente) {
        this.continente = continente;
    }

    public String getRegionGeo() {
        return this.regionGeo;
    }

    public void setRegionGeo(String regionGeo) {
        this.regionGeo = regionGeo;
    }

    public String getEscapital() {
        return this.escapital;
    }

    public void setEscapital(String escapital) {
        this.escapital = escapital;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public Long getNivel() {
        return this.nivel;
    }

    public void setNivel(Long nivel) {
        this.nivel = nivel;
    }

    public int getPadre() {
        return this.padre;
    }

    public void setPadre(int padre) {
        this.padre = padre;
    }

    public String getCodigoOficial() {
        return this.codigoOficial;
    }

    public void setCodigoOficial(String codigoOficial) {
        this.codigoOficial = codigoOficial;
    }

    public String getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(String estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public String getIdZona() {
        return this.idZona;
    }

    public void setIdZona(String idZona) {
        this.idZona = idZona;
    }

    public String getCodigoSri() {
        return this.codigoSri;
    }

    public void setCodigoSri(String codigoSri) {
        this.codigoSri = codigoSri;
    }

    public Set getTitulosProfesionaleses() {
        return titulosProfesionaleses;
    }

    public void setTitulosProfesionaleses(Set titulosProfesionaleses) {
        this.titulosProfesionaleses = titulosProfesionaleses;
    }

    public DefaultMutableTreeNode getNodo() {
        return Nodo;
    }

    public void setNodo(DefaultMutableTreeNode Nodo) {
        this.Nodo = Nodo;
    }




}
