package datos.pojos.adminuc;
// Generated 06/12/2011 05:07:25 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private String personId;
     private String login;
     private String nombreCorto;
     private String contrasenia;
     private String estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set rolesUsuarioses = new HashSet(0);

    public Usuarios() {
    }

	
    public Usuarios(String personId, String login, String nombreCorto, String contrasenia, String estaactivo, String creado, Date fechaCreacion) {
        this.personId = personId;
        this.login = login;
        this.nombreCorto = nombreCorto;
        this.contrasenia = contrasenia;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public Usuarios(String personId, String login, String nombreCorto, String contrasenia, String estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set rolesUsuarioses) {
       this.personId = personId;
       this.login = login;
       this.nombreCorto = nombreCorto;
       this.contrasenia = contrasenia;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.rolesUsuarioses = rolesUsuarioses;
    }
   
    public String getPersonId() {
        return this.personId;
    }
    
    public void setPersonId(String personId) {
        this.personId = personId;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getNombreCorto() {
        return this.nombreCorto;
    }
    
    public void setNombreCorto(String nombreCorto) {
        this.nombreCorto = nombreCorto;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public String getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(String estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getRolesUsuarioses() {
        return this.rolesUsuarioses;
    }
    
    public void setRolesUsuarioses(Set rolesUsuarioses) {
        this.rolesUsuarioses = rolesUsuarioses;
    }




}


