package datos.pojos.adminuc;
// Generated 29/02/2012 12:51:41 PM by Hibernate Tools 3.2.1.GA


import acceso.Consultas;
import acceso.ParametrosConsulta;
import acceso.db;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 * ValidacionLogin generated by hbm2java
 */
public class ValidacionLogin  implements java.io.Serializable {


     private int id;
     private String usuario;
     private String validacion;
     private Date fecha;
     private String usuarioEncriptado;

    public ValidacionLogin() {
    }

	
    public ValidacionLogin(int id) {
        this.id = id;
    }
    public ValidacionLogin(int id, String usuario, String validacion, Date fecha, String usuarioEncriptado) {
       this.id = id;
       this.usuario = usuario;
       this.validacion = validacion;
       this.fecha = fecha;
       this.usuarioEncriptado = usuarioEncriptado;
    }
    
    
      public List<ValidacionLogin> validacionXUsuario(String usuario) {
        String objeto = "ValidacionLogin";
        String where = "where usuarioEncriptado= :idUsuario ";
        List<ParametrosConsulta> lisPar = new ArrayList();
        lisPar.add(new ParametrosConsulta("idUsuario", usuario));
        Consultas consulta = new Consultas();
        try {
            return consulta.getListHql(null, objeto, where, lisPar);
        } catch (Exception e) {
            return null;
        }
    }

    public void borrarUsuario(ValidacionLogin usuValidado) {
        Transaction tx = null;
        try {
            Session session = db.abrirSesion();
            tx = session.beginTransaction();
            session.delete(usuValidado);
            tx.commit();
            //System.out.println("Borra Usuario");
            db.cerrarSesion();
        } catch (Exception e) {
            // System.out.println("Catch Borra Usuario"+e.getMessage().toString());
            tx.rollback();
            db.cerrarSesion();
        }
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getValidacion() {
        return this.validacion;
    }
    
    public void setValidacion(String validacion) {
        this.validacion = validacion;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public String getUsuarioEncriptado() {
        return this.usuarioEncriptado;
    }
    
    public void setUsuarioEncriptado(String usuarioEncriptado) {
        this.usuarioEncriptado = usuarioEncriptado;
    }




}


