package datos.pojos.academico;
// Generated 30/01/2012 09:23:17 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgaPeriodosLectivos generated by hbm2java
 */
public class SgaPeriodosLectivos  implements java.io.Serializable {


     private int id;
     private Date fechainicio;
     private Date fechafin;
     private String descripcion;
     private char envigencia;
     private char enuso;
     private char cerrado;
     private String descripcionanual;
     private String estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private String abreviatura;
     private Character vigenteInscripciones;
     private Character vigenteSocioeconomica;
     private String nombreInternado;
     private Character vigenteCalificaciones;
     private String abreviaturaanual;
     private String abreviaturainternado;

    public SgaPeriodosLectivos() {
    }

	
    public SgaPeriodosLectivos(int id, Date fechainicio, Date fechafin, String descripcion, char envigencia, char enuso, char cerrado, String estaactivo, String creado, Date fechaCreacion, String abreviatura) {
        this.id = id;
        this.fechainicio = fechainicio;
        this.fechafin = fechafin;
        this.descripcion = descripcion;
        this.envigencia = envigencia;
        this.enuso = enuso;
        this.cerrado = cerrado;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.abreviatura = abreviatura;
    }
    public SgaPeriodosLectivos(int id, Date fechainicio, Date fechafin, String descripcion, char envigencia, char enuso, char cerrado, String descripcionanual, String estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, String abreviatura, Character vigenteInscripciones, Character vigenteSocioeconomica, String nombreInternado, Character vigenteCalificaciones, String abreviaturaanual, String abreviaturainternado) {
       this.id = id;
       this.fechainicio = fechainicio;
       this.fechafin = fechafin;
       this.descripcion = descripcion;
       this.envigencia = envigencia;
       this.enuso = enuso;
       this.cerrado = cerrado;
       this.descripcionanual = descripcionanual;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.abreviatura = abreviatura;
       this.vigenteInscripciones = vigenteInscripciones;
       this.vigenteSocioeconomica = vigenteSocioeconomica;
       this.nombreInternado = nombreInternado;
       this.vigenteCalificaciones = vigenteCalificaciones;
       this.abreviaturaanual = abreviaturaanual;
       this.abreviaturainternado = abreviaturainternado;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Date getFechainicio() {
        return this.fechainicio;
    }
    
    public void setFechainicio(Date fechainicio) {
        this.fechainicio = fechainicio;
    }
    public Date getFechafin() {
        return this.fechafin;
    }
    
    public void setFechafin(Date fechafin) {
        this.fechafin = fechafin;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public char getEnvigencia() {
        return this.envigencia;
    }
    
    public void setEnvigencia(char envigencia) {
        this.envigencia = envigencia;
    }
    public char getEnuso() {
        return this.enuso;
    }
    
    public void setEnuso(char enuso) {
        this.enuso = enuso;
    }
    public char getCerrado() {
        return this.cerrado;
    }
    
    public void setCerrado(char cerrado) {
        this.cerrado = cerrado;
    }
    public String getDescripcionanual() {
        return this.descripcionanual;
    }
    
    public void setDescripcionanual(String descripcionanual) {
        this.descripcionanual = descripcionanual;
    }
    public String getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(String estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public Character getVigenteInscripciones() {
        return this.vigenteInscripciones;
    }
    
    public void setVigenteInscripciones(Character vigenteInscripciones) {
        this.vigenteInscripciones = vigenteInscripciones;
    }
    public Character getVigenteSocioeconomica() {
        return this.vigenteSocioeconomica;
    }
    
    public void setVigenteSocioeconomica(Character vigenteSocioeconomica) {
        this.vigenteSocioeconomica = vigenteSocioeconomica;
    }
    public String getNombreInternado() {
        return this.nombreInternado;
    }
    
    public void setNombreInternado(String nombreInternado) {
        this.nombreInternado = nombreInternado;
    }
    public Character getVigenteCalificaciones() {
        return this.vigenteCalificaciones;
    }
    
    public void setVigenteCalificaciones(Character vigenteCalificaciones) {
        this.vigenteCalificaciones = vigenteCalificaciones;
    }
    public String getAbreviaturaanual() {
        return this.abreviaturaanual;
    }
    
    public void setAbreviaturaanual(String abreviaturaanual) {
        this.abreviaturaanual = abreviaturaanual;
    }
    public String getAbreviaturainternado() {
        return this.abreviaturainternado;
    }
    
    public void setAbreviaturainternado(String abreviaturainternado) {
        this.abreviaturainternado = abreviaturainternado;
    }




}


