package datos.pojos.sgap;
// Generated 27/02/2014 04:06:17 PM by Hibernate Tools 3.2.1.GA



/**
 * SgpActasConfiguracionesId generated by hbm2java
 */
public class SgpActasConfiguracionesId  implements java.io.Serializable {


     private int accId;
     private int accActaId;
     private int accCurposId;
     private int accEdicionId;

    public SgpActasConfiguracionesId() {
    }

    public SgpActasConfiguracionesId(int accId, int accActaId, int accCurposId, int accEdicionId) {
       this.accId = accId;
       this.accActaId = accActaId;
       this.accCurposId = accCurposId;
       this.accEdicionId = accEdicionId;
    }
   
    public int getAccId() {
        return this.accId;
    }
    
    public void setAccId(int accId) {
        this.accId = accId;
    }
    public int getAccActaId() {
        return this.accActaId;
    }
    
    public void setAccActaId(int accActaId) {
        this.accActaId = accActaId;
    }
    public int getAccCurposId() {
        return this.accCurposId;
    }
    
    public void setAccCurposId(int accCurposId) {
        this.accCurposId = accCurposId;
    }
    public int getAccEdicionId() {
        return this.accEdicionId;
    }
    
    public void setAccEdicionId(int accEdicionId) {
        this.accEdicionId = accEdicionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpActasConfiguracionesId) ) return false;
		 SgpActasConfiguracionesId castOther = ( SgpActasConfiguracionesId ) other; 
         
		 return (this.getAccId()==castOther.getAccId())
 && (this.getAccActaId()==castOther.getAccActaId())
 && (this.getAccCurposId()==castOther.getAccCurposId())
 && (this.getAccEdicionId()==castOther.getAccEdicionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAccId();
         result = 37 * result + this.getAccActaId();
         result = 37 * result + this.getAccCurposId();
         result = 37 * result + this.getAccEdicionId();
         return result;
   }   


}


