package datos.pojos.sgap;
// Generated 27/02/2014 04:06:17 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpActasConfiguraciones generated by hbm2java
 */
public class SgpActasConfiguraciones  implements java.io.Serializable {


     private SgpActasConfiguracionesId id;
     private SgpActas sgpActas;
     private String accNombre;
     private short accPorcentajeIncidencia;
     private char accInfluyeCalculo;
     private String accTipo;
     private String accFormula;
     private char accRedondea;
     private byte accNumeroDecimales;
     private char accEstaactivo;
     private String accCreado;
     private Date accFechaCreacion;
     private String accActualizado;
     private Date accFechaActualizacion;
     private boolean _nuevo;
     private boolean _modificado;
     private boolean _eliminado;

    public SgpActasConfiguraciones() {
    }

	
    public SgpActasConfiguraciones(SgpActasConfiguracionesId id, SgpActas sgpActas, String accNombre, short accPorcentajeIncidencia, char accInfluyeCalculo, String accTipo, String accFormula, char accRedondea, byte accNumeroDecimales, char accEstaactivo, String accCreado, Date accFechaCreacion) {
        this.id = id;
        this.sgpActas = sgpActas;
        this.accNombre = accNombre;
        this.accPorcentajeIncidencia = accPorcentajeIncidencia;
        this.accInfluyeCalculo = accInfluyeCalculo;
        this.accTipo = accTipo;
        this.accFormula = accFormula;
        this.accRedondea = accRedondea;
        this.accNumeroDecimales = accNumeroDecimales;
        this.accEstaactivo = accEstaactivo;
        this.accCreado = accCreado;
        this.accFechaCreacion = accFechaCreacion;
    }
    public SgpActasConfiguraciones(SgpActasConfiguracionesId id, SgpActas sgpActas, String accNombre, short accPorcentajeIncidencia, char accInfluyeCalculo, String accTipo, String accFormula, char accRedondea, byte accNumeroDecimales, char accEstaactivo, String accCreado, Date accFechaCreacion, String accActualizado, Date accFechaActualizacion) {
       this.id = id;
       this.sgpActas = sgpActas;
       this.accNombre = accNombre;
       this.accPorcentajeIncidencia = accPorcentajeIncidencia;
       this.accInfluyeCalculo = accInfluyeCalculo;
       this.accTipo = accTipo;
       this.accFormula = accFormula;
       this.accRedondea = accRedondea;
       this.accNumeroDecimales = accNumeroDecimales;
       this.accEstaactivo = accEstaactivo;
       this.accCreado = accCreado;
       this.accFechaCreacion = accFechaCreacion;
       this.accActualizado = accActualizado;
       this.accFechaActualizacion = accFechaActualizacion;
    }
   
    public SgpActasConfiguracionesId getId() {
        return this.id;
    }
    
    public void setId(SgpActasConfiguracionesId id) {
        this.id = id;
    }
    public SgpActas getSgpActas() {
        return this.sgpActas;
    }
    
    public void setSgpActas(SgpActas sgpActas) {
        this.sgpActas = sgpActas;
    }
    public String getAccNombre() {
        return this.accNombre;
    }
    
    public void setAccNombre(String accNombre) {
        this.accNombre = accNombre;
    }
    public short getAccPorcentajeIncidencia() {
        return this.accPorcentajeIncidencia;
    }
    
    public void setAccPorcentajeIncidencia(short accPorcentajeIncidencia) {
        this.accPorcentajeIncidencia = accPorcentajeIncidencia;
    }
    public char getAccInfluyeCalculo() {
        return this.accInfluyeCalculo;
    }
    
    public void setAccInfluyeCalculo(char accInfluyeCalculo) {
        this.accInfluyeCalculo = accInfluyeCalculo;
    }
    public String getAccTipo() {
        return this.accTipo;
    }
    
    public void setAccTipo(String accTipo) {
        this.accTipo = accTipo;
    }
    public String getAccFormula() {
        return this.accFormula;
    }
    
    public void setAccFormula(String accFormula) {
        this.accFormula = accFormula;
    }
    public char getAccRedondea() {
        return this.accRedondea;
    }
    
    public void setAccRedondea(char accRedondea) {
        this.accRedondea = accRedondea;
    }
    public byte getAccNumeroDecimales() {
        return this.accNumeroDecimales;
    }
    
    public void setAccNumeroDecimales(byte accNumeroDecimales) {
        this.accNumeroDecimales = accNumeroDecimales;
    }
    public char getAccEstaactivo() {
        return this.accEstaactivo;
    }
    
    public void setAccEstaactivo(char accEstaactivo) {
        this.accEstaactivo = accEstaactivo;
    }
    public String getAccCreado() {
        return this.accCreado;
    }
    
    public void setAccCreado(String accCreado) {
        this.accCreado = accCreado;
    }
    public Date getAccFechaCreacion() {
        return this.accFechaCreacion;
    }
    
    public void setAccFechaCreacion(Date accFechaCreacion) {
        this.accFechaCreacion = accFechaCreacion;
    }
    public String getAccActualizado() {
        return this.accActualizado;
    }
    
    public void setAccActualizado(String accActualizado) {
        this.accActualizado = accActualizado;
    }
    public Date getAccFechaActualizacion() {
        return this.accFechaActualizacion;
    }
    
    public void setAccFechaActualizacion(Date accFechaActualizacion) {
        this.accFechaActualizacion = accFechaActualizacion;
    }

    public boolean isNuevo() {
        return _nuevo;
    }

    public void setNuevo(boolean _nuevo) {
        this._nuevo = _nuevo;
    }

    public boolean isModificado() {
        return _modificado;
    }

    public void setModificado(boolean _modificado) {
        this._modificado = _modificado;
    }

    public boolean isEliminado() {
        return _eliminado;
    }

    public void setEliminado(boolean _eliminado) {
        this._eliminado = _eliminado;
    }
    
}


