package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpActividadesOfertas generated by hbm2java
 */
public class SgpActividadesOfertas  implements java.io.Serializable {


     private SgpActividadesOfertasId id;
     private SgpActividadesCronograma sgpActividadesCronograma;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpActividadesOfertas() {
    }

	
    public SgpActividadesOfertas(SgpActividadesOfertasId id, SgpActividadesCronograma sgpActividadesCronograma, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpActividadesCronograma = sgpActividadesCronograma;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpActividadesOfertas(SgpActividadesOfertasId id, SgpActividadesCronograma sgpActividadesCronograma, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpActividadesCronograma = sgpActividadesCronograma;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public SgpActividadesOfertasId getId() {
        return this.id;
    }
    
    public void setId(SgpActividadesOfertasId id) {
        this.id = id;
    }
    public SgpActividadesCronograma getSgpActividadesCronograma() {
        return this.sgpActividadesCronograma;
    }
    
    public void setSgpActividadesCronograma(SgpActividadesCronograma sgpActividadesCronograma) {
        this.sgpActividadesCronograma = sgpActividadesCronograma;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


