package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpAsignaturas generated by hbm2java
 */
public class SgpAsignaturas implements java.io.Serializable {

    private int id;
    private SgpEjesFormacion sgpEjesFormacion;
    private String codigo;
    private String nombre;
    private String nombreLargo;
    private String abreviatura;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private Set sgpAsignaturasMallases = new HashSet(0);
    private Set sgpOfertaAsignaturas = new HashSet(0);
    private Set sgpUnidadesMallas = new HashSet(0);
    private boolean _selected = false;
    private Integer horasPresenciales;
    private Integer horasEstudiante;
    private Integer horasColaborativo;
    private Integer horasAplicacionExperimenta;
    private Integer totalHoras;
    private BigDecimal creditos;

    public SgpAsignaturas() {
    }

    public SgpAsignaturas(int id) {
        this.id = id;

    }

    public SgpAsignaturas(int id, String nombre, String nombreLargo, String abreviatura, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.nombreLargo = nombreLargo;
        this.abreviatura = abreviatura;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpAsignaturas(int id, String nombre, String nombreLargo, String abreviatura, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpAsignaturasMallases, Set sgpOfertaAsignaturas) {
        this.id = id;
        this.nombre = nombre;
        this.nombreLargo = nombreLargo;
        this.abreviatura = abreviatura;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.sgpAsignaturasMallases = sgpAsignaturasMallases;
        this.sgpOfertaAsignaturas = sgpOfertaAsignaturas;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getNombreLargo() {
        return this.nombreLargo;
    }

    public void setNombreLargo(String nombreLargo) {
        this.nombreLargo = nombreLargo;
    }

    public String getAbreviatura() {
        return this.abreviatura;
    }

    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Set getSgpOfertaAsignaturas() {
        return this.sgpOfertaAsignaturas;
    }

    public void setSgpOfertaAsignaturas(Set sgpOfertaAsignaturas) {
        this.sgpOfertaAsignaturas = sgpOfertaAsignaturas;
    }

    public Set getSgpAsignaturasMallases() {
        return sgpAsignaturasMallases;
    }

    public void setSgpAsignaturasMallases(Set sgpAsignaturasMallases) {
        this.sgpAsignaturasMallases = sgpAsignaturasMallases;
    }

    public boolean isSelected() {
        return _selected;
    }

    public void setSelected(boolean _selected) {
        this._selected = _selected;
    }

    public Integer getHorasPresenciales() {
        return horasPresenciales;
    }

    public void setHorasPresenciales(Integer horasPresenciales) {
        this.horasPresenciales = horasPresenciales;
    }

    public Integer getHorasEstudiante() {
        return horasEstudiante;
    }

    public void setHorasEstudiante(Integer horasEstudiante) {
        this.horasEstudiante = horasEstudiante;
    }

    public Integer getTotalHoras() {
        return totalHoras;
    }

    public void setTotalHoras(Integer totalHoras) {
        this.totalHoras = totalHoras;
    }

    public BigDecimal getCreditos() {
        return creditos;
    }

    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }

  
    public Integer getHorasAplicacionExperimenta() {
        return horasAplicacionExperimenta;
    }

    public void setHorasAplicacionExperimenta(Integer horasAplicacionExperimenta) {
        this.horasAplicacionExperimenta = horasAplicacionExperimenta;
    }

    public Integer getHorasColaborativo() {
        return horasColaborativo;
    }

    public void setHorasColaborativo(Integer horasColaborativo) {
        this.horasColaborativo = horasColaborativo;
    }

    public String getCodigo() {
        return codigo;
    }

    public void setCodigo(String codigo) {
        this.codigo = codigo;
    }

    public SgpEjesFormacion getSgpEjesFormacion() {
        return sgpEjesFormacion;
    }

    public void setSgpEjesFormacion(SgpEjesFormacion sgpEjesFormacion) {
        this.sgpEjesFormacion = sgpEjesFormacion;
    }

    public Set getSgpUnidadesMallas() {
        return sgpUnidadesMallas;
    }

    public void setSgpUnidadesMallas(Set sgpUnidadesMallas) {
        this.sgpUnidadesMallas = sgpUnidadesMallas;
    }
}
