package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * SgpAsignaturasMallas generated by hbm2java
 */
public class SgpAsignaturasMallas implements java.io.Serializable {

    private SgpAsignaturasMallasId id;
    private SgpFormasEvaluacion sgpFormasEvaluacion;
    private SgpEjesFormacion sgpEjesFormacion;
    // private SgpEjesTematicos sgpEjesTematicos;
    private Integer ejetemId;
    private SgpUnidadesOrganizacion sgpUnidadesOrganizacion;
    private SgpAsignaturas sgpAsignaturas;
    private SgpMallas sgpMallas;
    private Integer horasPresenciales;
    private Integer horasEstudiante;
    private Integer totalHoras;
    private BigDecimal creditos;
    private char esremediable;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private Set sgpMencionesAsignaturases = new HashSet(0);
    private Set sgpSilaboses = new HashSet(0);
    private Set sgpDocentesAsignaturases = new HashSet(0);
    private String esobligatoria;
    private String eselectiva;
    private Integer horasColaborativo;
    private Integer horasAplicacionExperimenta;
    //otro
    private boolean _selected = false;
    private boolean _selectedOpc = false;
    private boolean _selectOblig = false;
    private String _nomAsignatura = "";
    private int _idAsignatura;
    private String _hEstudiante = "";
    private String _hPresenciales = "";
    private String _hTotal = "";
    private Integer codAsignatura;
    private String _uOrganizadora = "";
    private Integer _uOrganizadoraId;
    private String _txthorasObligatorias;
    private String _txthorasOpcionales;
    private String _txtTotalHoras;
    private Integer _hObligatorias = 0;
    private Integer _hElectivas = 0;
    private Integer _hTotalHoras = 0;
    private DecimalFormat df00 = new DecimalFormat("00");
    private DecimalFormat df000 = new DecimalFormat("000");
    
    private String _hColaborativo;
    private String _hExperimentacion;
    private Integer nivel;

    public SgpAsignaturasMallas() {
    }

    public SgpAsignaturasMallas(SgpAsignaturasMallasId id, SgpFormasEvaluacion sgpFormasEvaluacion, SgpEjesFormacion sgpEjesFormacion, SgpAsignaturas sgpAsignaturas, SgpMallas sgpMallas, BigDecimal creditos, char esremediable, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpFormasEvaluacion = sgpFormasEvaluacion;
        this.sgpEjesFormacion = sgpEjesFormacion;
        //  this.sgpEjesTematicos = sgpEjesTematicos;
        this.sgpAsignaturas = sgpAsignaturas;
        this.sgpMallas = sgpMallas;
        this.creditos = creditos;
        this.esremediable = esremediable;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpAsignaturasMallas(SgpAsignaturasMallasId id, SgpFormasEvaluacion sgpFormasEvaluacion, SgpEjesFormacion sgpEjesFormacion, SgpAsignaturas sgpAsignaturas, SgpMallas sgpMallas, Integer horasPresenciales, Integer horasEstudiante, Integer totalHoras, BigDecimal creditos, char esremediable, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpMencionesAsignaturases, Set sgpSilaboses, Set sgpDocentesAsignaturases) {
        this.id = id;
        this.sgpFormasEvaluacion = sgpFormasEvaluacion;
        this.sgpEjesFormacion = sgpEjesFormacion;
        // this.sgpEjesTematicos = sgpEjesTematicos;
        this.sgpAsignaturas = sgpAsignaturas;
        this.sgpMallas = sgpMallas;
        this.horasPresenciales = horasPresenciales;
        this.horasEstudiante = horasEstudiante;
        this.totalHoras = totalHoras;
        this.creditos = creditos;
        this.esremediable = esremediable;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.sgpMencionesAsignaturases = sgpMencionesAsignaturases;
        this.sgpSilaboses = sgpSilaboses;
        this.sgpDocentesAsignaturases = sgpDocentesAsignaturases;
    }

    public SgpAsignaturasMallasId getId() {
        return this.id;
    }

    public void setId(SgpAsignaturasMallasId id) {
        this.id = id;
    }

    public SgpFormasEvaluacion getSgpFormasEvaluacion() {
        return this.sgpFormasEvaluacion;
    }

    public void setSgpFormasEvaluacion(SgpFormasEvaluacion sgpFormasEvaluacion) {
        this.sgpFormasEvaluacion = sgpFormasEvaluacion;
    }

    public SgpEjesFormacion getSgpEjesFormacion() {
        return this.sgpEjesFormacion;
    }

    public void setSgpEjesFormacion(SgpEjesFormacion sgpEjesFormacion) {
        this.sgpEjesFormacion = sgpEjesFormacion;
    }

//    public SgpEjesTematicos getSgpEjesTematicos() {
//        return this.sgpEjesTematicos;
//    }
//
//    public void setSgpEjesTematicos(SgpEjesTematicos sgpEjesTematicos) {
//        this.sgpEjesTematicos = sgpEjesTematicos;
//    }
    public SgpMallas getSgpMallas() {
        return this.sgpMallas;
    }

    public void setSgpMallas(SgpMallas sgpMallas) {
        this.sgpMallas = sgpMallas;
    }

    public Integer getHorasPresenciales() {
        return this.horasPresenciales;
    }

    public void setHorasPresenciales(Integer horasPresenciales) {
        this.horasPresenciales = horasPresenciales;
    }

    public Integer getHorasEstudiante() {
        return this.horasEstudiante;
    }

    public void setHorasEstudiante(Integer horasEstudiante) {
        this.horasEstudiante = horasEstudiante;
    }

    public Integer getTotalHoras() {
        return this.totalHoras;
    }

    public void setTotalHoras(Integer totalHoras) {
        this.totalHoras = totalHoras;
    }

    public BigDecimal getCreditos() {
        return creditos;
    }

    public void setCreditos(BigDecimal creditos) {
        this.creditos = creditos;
    }

   

    public char getEsremediable() {
        return this.esremediable;
    }

    public void setEsremediable(char esremediable) {
        this.esremediable = esremediable;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Set getSgpMencionesAsignaturases() {
        return this.sgpMencionesAsignaturases;
    }

    public void setSgpMencionesAsignaturases(Set sgpMencionesAsignaturases) {
        this.sgpMencionesAsignaturases = sgpMencionesAsignaturases;
    }

    public Set getSgpSilaboses() {
        return this.sgpSilaboses;
    }

    public void setSgpSilaboses(Set sgpSilaboses) {
        this.sgpSilaboses = sgpSilaboses;
    }

    public Set getSgpDocentesAsignaturases() {
        return this.sgpDocentesAsignaturases;
    }

    public void setSgpDocentesAsignaturases(Set sgpDocentesAsignaturases) {
        this.sgpDocentesAsignaturases = sgpDocentesAsignaturases;
    }

    public SgpAsignaturas getSgpAsignaturas() {
        return sgpAsignaturas;
    }

    public void setSgpAsignaturas(SgpAsignaturas sgpAsignaturas) {
        this.sgpAsignaturas = sgpAsignaturas;
    }

    public boolean isSelected() {
        return _selected;
    }

    public void setSelected(boolean _selected) {
        this._selected = _selected;
    }

    public int getIdAsignatura() {
        return _idAsignatura;
    }

    public void setIdAsignatura(int _idAsignatura) {
        this._idAsignatura = _idAsignatura;
    }

    public String getNomAsignatura() {
        return _nomAsignatura;
    }

    public void setNomAsignatura(String _nomAsignatura) {
        this._nomAsignatura = _nomAsignatura;
    }

    public String gethEstudiante() {
        return _hEstudiante;
    }

    public void sethEstudiante(String _hEstudiante) {
        this._hEstudiante = _hEstudiante;
    }

    public String gethPresenciales() {
        return _hPresenciales;
    }

    public void sethPresenciales(String _hPresenciales) {
        this._hPresenciales = _hPresenciales;
    }

    public String gethTotal() {

        try {
            if (totalHoras != null) {
                int horas = (int) Math.floor(totalHoras / 60);
                int minutos = totalHoras % 60;
                String longT = String.valueOf(horas);
                if (longT.length() == 3) {
                    _hTotal = (df000.format(horas) + ":" + df00.format(minutos));
                } else {
                    _hTotal = (df00.format(horas) + ":" + df00.format(minutos));
                }

            } else {
                _hTotal = "00:00";
            }
        } catch (Exception e) {
            _hTotal = "000:00";
        }
        return _hTotal;
    }

    public void sethTotal(String _hTotal) {
        this._hTotal = _hTotal;
    }

    public SgpUnidadesOrganizacion getSgpUnidadesOrganizacion() {
        return sgpUnidadesOrganizacion;
    }

    public void setSgpUnidadesOrganizacion(SgpUnidadesOrganizacion sgpUnidadesOrganizacion) {
        this.sgpUnidadesOrganizacion = sgpUnidadesOrganizacion;
    }

    public String getEsobligatoria() {
        return esobligatoria;
    }

    public void setEsobligatoria(String esobligatoria) {
        this.esobligatoria = esobligatoria;
    }

    public String getEselectiva() {
        return eselectiva;
    }

    public void setEselectiva(String eselectiva) {
        this.eselectiva = eselectiva;
    }

    public Integer getHorasColaborativo() {
        return horasColaborativo;
    }

    public void setHorasColaborativo(Integer horasColaborativo) {
        this.horasColaborativo = horasColaborativo;
    }

    public Integer getHorasAplicacionExperimenta() {
        return horasAplicacionExperimenta;
    }

    public void setHorasAplicacionExperimenta(Integer horasAplicacionExperimenta) {
        this.horasAplicacionExperimenta = horasAplicacionExperimenta;
    }

    public Integer getEjetemId() {
        return ejetemId;
    }

    public void setEjetemId(Integer ejetemId) {
        this.ejetemId = ejetemId;
    }

    public Integer getCodAsignatura() {
        return codAsignatura;
    }

    public void setCodAsignatura(Integer codAsignatura) {
        this.codAsignatura = codAsignatura;
    }

    public boolean isSelectOblig() {
        return _selectOblig;
    }

    public void setSelectOblig(boolean selectOblig) {
        this._selectOblig = selectOblig;
    }

    public boolean isSelectedOpc() {
        return _selectedOpc;
    }

    public void setSelectedOpc(boolean selectedOpc) {
        this._selectedOpc = selectedOpc;
    }

    public String getuOrganizadora() {
        // _uOrganizadora=sgpUnidadesOrganizacion.getUnoNombre();
        return _uOrganizadora;
    }

    public void setuOrganizadora(String uOrganizadora) {
        this._uOrganizadora = uOrganizadora;
    }

    public Integer getuOrganizadoraId() {
        //  _uOrganizadoraId= sgpUnidadesOrganizacion.getUnoId();
        return _uOrganizadoraId;
    }

    public void setuOrganizadoraId(Integer uOrganizadoraId) {
        this._uOrganizadoraId = uOrganizadoraId;
    }

    public String getTxthorasObligatorias() {
        return _txthorasObligatorias;
    }

    public void setTxthorasObligatorias(String _txthorasObligatorias) {
        this._txthorasObligatorias = _txthorasObligatorias;
    }

    public String getTxthorasOpcionales() {
        return _txthorasOpcionales;
    }

    public void setTxthorasOpcionales(String _txthorasOpcionales) {
        this._txthorasOpcionales = _txthorasOpcionales;
    }

    public String getTxtTotalHoras() {
        return _txtTotalHoras;
    }

    public void setTxtTotalHoras(String _txtTotalHoras) {
        this._txtTotalHoras = _txtTotalHoras;
    }

    public Integer gethObligatorias() {
        return _hObligatorias;
    }

    public void sethObligatorias(Integer _hObligatorias) {
        this._hObligatorias = _hObligatorias;
    }

    public Integer gethElectivas() {
        return _hElectivas;
    }

    public void sethElectivas(Integer _hElectivas) {
        this._hElectivas = _hElectivas;
    }

    public Integer gethTotalHoras() {
        return _hTotalHoras;
    }

    public void sethTotalHoras(Integer _hTotalHoras) {
        this._hTotalHoras = _hTotalHoras;
    }
    
     public String gethColaborativo() {
        return _hColaborativo;
    }

    public void sethColaborativo(String _hColaborativo) {
        this._hColaborativo = _hColaborativo;
    }

    public String gethExperimentacion() {
        return _hExperimentacion;
    }

    public void sethExperimentacion(String _hExperimentacion) {
        this._hExperimentacion = _hExperimentacion;
    }

    public Integer getNivel() {
        return nivel;
    }

    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
}
