package datos.pojos.sgap;
// Generated 28/03/2014 04:35:23 PM by Hibernate Tools 3.2.1.GA



/**
 * SgpActaEstudianteId generated by hbm2java
 */
public class SgpActaEstudianteId  implements java.io.Serializable {


     private String acePersonaId;
     private int aceCurposId;
     private int aceEdicionId;

    public SgpActaEstudianteId() {
    }

    public SgpActaEstudianteId(String acePersonaId, int aceCurposId, int aceEdicionId) {
       this.acePersonaId = acePersonaId;
       this.aceCurposId = aceCurposId;
       this.aceEdicionId = aceEdicionId;
    }
   
    public String getAcePersonaId() {
        return this.acePersonaId;
    }
    
    public void setAcePersonaId(String acePersonaId) {
        this.acePersonaId = acePersonaId;
    }
    public int getAceCurposId() {
        return this.aceCurposId;
    }
    
    public void setAceCurposId(int aceCurposId) {
        this.aceCurposId = aceCurposId;
    }
    public int getAceEdicionId() {
        return this.aceEdicionId;
    }
    
    public void setAceEdicionId(int aceEdicionId) {
        this.aceEdicionId = aceEdicionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpActaEstudianteId) ) return false;
		 SgpActaEstudianteId castOther = ( SgpActaEstudianteId ) other; 
         
		 return ( (this.getAcePersonaId()==castOther.getAcePersonaId()) || ( this.getAcePersonaId()!=null && castOther.getAcePersonaId()!=null && this.getAcePersonaId().equals(castOther.getAcePersonaId()) ) )
 && (this.getAceCurposId()==castOther.getAceCurposId())
 && (this.getAceEdicionId()==castOther.getAceEdicionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getAcePersonaId() == null ? 0 : this.getAcePersonaId().hashCode() );
         result = 37 * result + this.getAceCurposId();
         result = 37 * result + this.getAceEdicionId();
         return result;
   }   


}


