package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpActividadesTitulacionId generated by hbm2java
 */
public class SgpActividadesTitulacionId  implements java.io.Serializable {


     private int id;
     private int tratitId;

    public SgpActividadesTitulacionId() {
    }

    public SgpActividadesTitulacionId(int id, int tratitId) {
       this.id = id;
       this.tratitId = tratitId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getTratitId() {
        return this.tratitId;
    }
    
    public void setTratitId(int tratitId) {
        this.tratitId = tratitId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpActividadesTitulacionId) ) return false;
		 SgpActividadesTitulacionId castOther = ( SgpActividadesTitulacionId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getTratitId()==castOther.getTratitId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getTratitId();
         return result;
   }   


}


