package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpActividadesOfertasId generated by hbm2java
 */
public class SgpActividadesOfertasId  implements java.io.Serializable {


     private int actcroId;
     private int placarId;
     private int curposId;
     private int edicionId;
     private int perlecId;
     private int asignaturaId;
     private int grupo;

    public SgpActividadesOfertasId() {
    }

    public SgpActividadesOfertasId(int actcroId, int placarId, int curposId, int edicionId, int perlecId, int asignaturaId, int grupo) {
       this.actcroId = actcroId;
       this.placarId = placarId;
       this.curposId = curposId;
       this.edicionId = edicionId;
       this.perlecId = perlecId;
       this.asignaturaId = asignaturaId;
       this.grupo = grupo;
    }
   
    public int getActcroId() {
        return this.actcroId;
    }
    
    public void setActcroId(int actcroId) {
        this.actcroId = actcroId;
    }
    public int getPlacarId() {
        return this.placarId;
    }
    
    public void setPlacarId(int placarId) {
        this.placarId = placarId;
    }
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }
    public int getPerlecId() {
        return this.perlecId;
    }
    
    public void setPerlecId(int perlecId) {
        this.perlecId = perlecId;
    }
    public int getAsignaturaId() {
        return this.asignaturaId;
    }
    
    public void setAsignaturaId(int asignaturaId) {
        this.asignaturaId = asignaturaId;
    }
    public int getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(int grupo) {
        this.grupo = grupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpActividadesOfertasId) ) return false;
		 SgpActividadesOfertasId castOther = ( SgpActividadesOfertasId ) other; 
         
		 return (this.getActcroId()==castOther.getActcroId())
 && (this.getPlacarId()==castOther.getPlacarId())
 && (this.getCurposId()==castOther.getCurposId())
 && (this.getEdicionId()==castOther.getEdicionId())
 && (this.getPerlecId()==castOther.getPerlecId())
 && (this.getAsignaturaId()==castOther.getAsignaturaId())
 && (this.getGrupo()==castOther.getGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getActcroId();
         result = 37 * result + this.getPlacarId();
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getEdicionId();
         result = 37 * result + this.getPerlecId();
         result = 37 * result + this.getAsignaturaId();
         result = 37 * result + this.getGrupo();
         return result;
   }   


}


