package datos.pojos.sgap;
// Generated 27/02/2014 04:06:17 PM by Hibernate Tools 3.2.1.GA



/**
 * SgpActaAutorizacionId generated by hbm2java
 */
public class SgpActaAutorizacionId  implements java.io.Serializable {


     private int acaId;
     private String acaPersonaId;
     private int acaCurposId;
     private int acaEdicionId;

    public SgpActaAutorizacionId() {
    }

    public SgpActaAutorizacionId(int acaId, String acaPersonaId, int acaCurposId, int acaEdicionId) {
       this.acaId = acaId;
       this.acaPersonaId = acaPersonaId;
       this.acaCurposId = acaCurposId;
       this.acaEdicionId = acaEdicionId;
    }
   
    public int getAcaId() {
        return this.acaId;
    }
    
    public void setAcaId(int acaId) {
        this.acaId = acaId;
    }
    public String getAcaPersonaId() {
        return this.acaPersonaId;
    }
    
    public void setAcaPersonaId(String acaPersonaId) {
        this.acaPersonaId = acaPersonaId;
    }
    public int getAcaCurposId() {
        return this.acaCurposId;
    }
    
    public void setAcaCurposId(int acaCurposId) {
        this.acaCurposId = acaCurposId;
    }
    public int getAcaEdicionId() {
        return this.acaEdicionId;
    }
    
    public void setAcaEdicionId(int acaEdicionId) {
        this.acaEdicionId = acaEdicionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpActaAutorizacionId) ) return false;
		 SgpActaAutorizacionId castOther = ( SgpActaAutorizacionId ) other; 
         
		 return (this.getAcaId()==castOther.getAcaId())
 && ( (this.getAcaPersonaId()==castOther.getAcaPersonaId()) || ( this.getAcaPersonaId()!=null && castOther.getAcaPersonaId()!=null && this.getAcaPersonaId().equals(castOther.getAcaPersonaId()) ) )
 && (this.getAcaCurposId()==castOther.getAcaCurposId())
 && (this.getAcaEdicionId()==castOther.getAcaEdicionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAcaId();
         result = 37 * result + ( getAcaPersonaId() == null ? 0 : this.getAcaPersonaId().hashCode() );
         result = 37 * result + this.getAcaCurposId();
         result = 37 * result + this.getAcaEdicionId();
         return result;
   }   


}


