package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpActividadesCronograma generated by hbm2java
 */
public class SgpActividadesCronograma implements java.io.Serializable {

    private SgpActividadesCronogramaId id;
    private SgpEdiciones sgpEdiciones;
    private String nombre;
    private Date fechaInicio;
    private Date fechaFin;
    private String orden;
    private String porcentajeAvance;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private Set sgpActividadesOfertases = new HashSet(0);
    private boolean _selected = false;
    private boolean _nuevo = false;
    private int _idx;

    public SgpActividadesCronograma() {
    }

    public SgpActividadesCronograma(SgpActividadesCronogramaId id, SgpEdiciones sgpEdiciones, String nombre, Date fechaInicio, Date fechaFin, String orden, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpEdiciones = sgpEdiciones;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.orden = orden;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpActividadesCronograma(SgpActividadesCronogramaId id, SgpEdiciones sgpEdiciones, String nombre, Date fechaInicio, Date fechaFin, String orden, String porcentajeAvance, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpActividadesOfertases) {
        this.id = id;
        this.sgpEdiciones = sgpEdiciones;
        this.nombre = nombre;
        this.fechaInicio = fechaInicio;
        this.fechaFin = fechaFin;
        this.orden = orden;
        this.porcentajeAvance = porcentajeAvance;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.sgpActividadesOfertases = sgpActividadesOfertases;
    }

    public SgpActividadesCronogramaId getId() {
        return this.id;
    }

    public void setId(SgpActividadesCronogramaId id) {
        this.id = id;
    }

    public SgpEdiciones getSgpEdiciones() {
        return sgpEdiciones;
    }

    public void setSgpEdiciones(SgpEdiciones sgpEdiciones) {
        this.sgpEdiciones = sgpEdiciones;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public Date getFechaInicio() {
        return this.fechaInicio;
    }

    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    public Date getFechaFin() {
        return this.fechaFin;
    }

    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

    public String getOrden() {
        return orden;
    }

    public void setOrden(String orden) {
        this.orden = orden;
    }

    public String getPorcentajeAvance() {
        return porcentajeAvance;
    }

    public void setPorcentajeAvance(String porcentajeAvance) {
        this.porcentajeAvance = porcentajeAvance;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Set getSgpActividadesOfertases() {
        return this.sgpActividadesOfertases;
    }

    public void setSgpActividadesOfertases(Set sgpActividadesOfertases) {
        this.sgpActividadesOfertases = sgpActividadesOfertases;
    }

    public boolean isSelected() {
        return _selected;
    }

    public void setSelected(boolean _selected) {
        this._selected = _selected;
    }

    public int getIdx() {
        return _idx;
    }

    public void setIdx(int _idx) {
        this._idx = _idx;
    }

    public boolean isNuevo() {
        return _nuevo;
    }

    public void setNuevo(boolean _nuevo) {
        this._nuevo = _nuevo;
    }
}
