package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpActividadesTitulacion generated by hbm2java
 */
public class SgpActividadesTitulacion  implements java.io.Serializable {


     private SgpActividadesTitulacionId id;
     private SgpTrabajosTitulacion sgpTrabajosTitulacion;
     private String nombre;
     private Date fechaInicia;
     private Date fechaTermina;
     private int orden;
     private Short porcentajeAvance;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpActividadesTitulacion() {
    }

	
    public SgpActividadesTitulacion(SgpActividadesTitulacionId id, SgpTrabajosTitulacion sgpTrabajosTitulacion, String nombre, int orden, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpTrabajosTitulacion = sgpTrabajosTitulacion;
        this.nombre = nombre;
        this.orden = orden;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpActividadesTitulacion(SgpActividadesTitulacionId id, SgpTrabajosTitulacion sgpTrabajosTitulacion, String nombre, Date fechaInicia, Date fechaTermina, int orden, Short porcentajeAvance, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpTrabajosTitulacion = sgpTrabajosTitulacion;
       this.nombre = nombre;
       this.fechaInicia = fechaInicia;
       this.fechaTermina = fechaTermina;
       this.orden = orden;
       this.porcentajeAvance = porcentajeAvance;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public SgpActividadesTitulacionId getId() {
        return this.id;
    }
    
    public void setId(SgpActividadesTitulacionId id) {
        this.id = id;
    }
    public SgpTrabajosTitulacion getSgpTrabajosTitulacion() {
        return this.sgpTrabajosTitulacion;
    }
    
    public void setSgpTrabajosTitulacion(SgpTrabajosTitulacion sgpTrabajosTitulacion) {
        this.sgpTrabajosTitulacion = sgpTrabajosTitulacion;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public Date getFechaInicia() {
        return this.fechaInicia;
    }
    
    public void setFechaInicia(Date fechaInicia) {
        this.fechaInicia = fechaInicia;
    }
    public Date getFechaTermina() {
        return this.fechaTermina;
    }
    
    public void setFechaTermina(Date fechaTermina) {
        this.fechaTermina = fechaTermina;
    }
    public int getOrden() {
        return this.orden;
    }
    
    public void setOrden(int orden) {
        this.orden = orden;
    }
    public Short getPorcentajeAvance() {
        return this.porcentajeAvance;
    }
    
    public void setPorcentajeAvance(Short porcentajeAvance) {
        this.porcentajeAvance = porcentajeAvance;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


