package datos.pojos.sgap;
// Generated 27/02/2014 04:34:12 PM by Hibernate Tools 3.2.1.GA



/**
 * SgpActasId generated by hbm2java
 */
public class SgpActasId  implements java.io.Serializable {


     private int actId;
     private int actCurposId;
     private int actEdicionId;

    public SgpActasId() {
    }

    public SgpActasId(int actId, int actCurposId, int actEdicionId) {
       this.actId = actId;
       this.actCurposId = actCurposId;
       this.actEdicionId = actEdicionId;
    }
   
    public int getActId() {
        return this.actId;
    }
    
    public void setActId(int actId) {
        this.actId = actId;
    }
    public int getActCurposId() {
        return this.actCurposId;
    }
    
    public void setActCurposId(int actCurposId) {
        this.actCurposId = actCurposId;
    }
    public int getActEdicionId() {
        return this.actEdicionId;
    }
    
    public void setActEdicionId(int actEdicionId) {
        this.actEdicionId = actEdicionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpActasId) ) return false;
		 SgpActasId castOther = ( SgpActasId ) other; 
         
		 return (this.getActId()==castOther.getActId())
 && (this.getActCurposId()==castOther.getActCurposId())
 && (this.getActEdicionId()==castOther.getActEdicionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getActId();
         result = 37 * result + this.getActCurposId();
         result = 37 * result + this.getActEdicionId();
         return result;
   }   


}


