package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpComponentesDetallesId generated by hbm2java
 */
public class SgpComponentesDetallesId  implements java.io.Serializable {


     private int cabcomId;
     private int componenteId;

    public SgpComponentesDetallesId() {
    }

    public SgpComponentesDetallesId(int cabcomId, int componenteId) {
       this.cabcomId = cabcomId;
       this.componenteId = componenteId;
    }
   
    public int getCabcomId() {
        return this.cabcomId;
    }
    
    public void setCabcomId(int cabcomId) {
        this.cabcomId = cabcomId;
    }
    public int getComponenteId() {
        return this.componenteId;
    }
    
    public void setComponenteId(int componenteId) {
        this.componenteId = componenteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpComponentesDetallesId) ) return false;
		 SgpComponentesDetallesId castOther = ( SgpComponentesDetallesId ) other; 
         
		 return (this.getCabcomId()==castOther.getCabcomId())
 && (this.getComponenteId()==castOther.getComponenteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCabcomId();
         result = 37 * result + this.getComponenteId();
         return result;
   }   


}


