package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import datos.pojos.adminuc.Dependencias;
import datos.pojos.adminuc.Titulos;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpCursosPostgrado generated by hbm2java
 */
public class SgpCursosPostgrado implements java.io.Serializable {

  private int id;
  private SgpDocumentosBinarios sgpDocumentosBinarios;
  private SgpSubareas sgpSubareas;
  private Dependencias dependencia;
  private String nombre;
  private String abreviatura;
  private Titulos titulo;
  private int nivforId;
  private Date fechaAprobacionFacultad;
  private Date fechaAprobacionDireccion;
  private String nroResolucionConsejo;
  private Date fechaAprobacionConsejo;
  private String estado;
  private String rolId;
  private char estaactivo;
  private String creado;
  private Date fechaCreacion;
  private String actualizado;
  private Date fechaActualizacion;
  private Set sgpTemases = new HashSet(0);
  private Set sgpPlanesCursos = new HashSet(0);
  private Set sgpResolucionesSenescyts = new HashSet(0);
  private Set sgpMatriculases = new HashSet(0);
  private String idFac = "";

  public SgpCursosPostgrado() {
  }

  public SgpCursosPostgrado(int id, SgpDocumentosBinarios sgpDocumentosBinarios, SgpSubareas sgpSubareas, Dependencias dependencia, String nombre, Titulos titulo, int nivforId, Date fechaAprobacionFacultad, Date fechaAprobacionDireccion, String nroResolucionConsejo, Date fechaAprobacionConsejo, String estado, char estaactivo, String creado, Date fechaCreacion) {
    this.id = id;
    this.sgpDocumentosBinarios = sgpDocumentosBinarios;
    this.sgpSubareas = sgpSubareas;
    this.dependencia = dependencia;
    this.nombre = nombre;
    this.titulo = titulo;
    this.nivforId = nivforId;
    this.fechaAprobacionFacultad = fechaAprobacionFacultad;
    this.fechaAprobacionDireccion = fechaAprobacionDireccion;
    this.nroResolucionConsejo = nroResolucionConsejo;
    this.fechaAprobacionConsejo = fechaAprobacionConsejo;
    this.estado = estado;
    this.estaactivo = estaactivo;
    this.creado = creado;
    this.fechaCreacion = fechaCreacion;
  }

  public SgpCursosPostgrado(int id, SgpDocumentosBinarios sgpDocumentosBinarios, SgpSubareas sgpSubareas, Dependencias dependencia, String nombre, String abreviatura, Titulos titulo, int nivforId, Date fechaAprobacionFacultad, Date fechaAprobacionDireccion, String nroResolucionConsejo, Date fechaAprobacionConsejo, String estado, String rolId, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpTemases, Set sgpPlanesCursos, Set sgpResolucionesSenescyts, Set sgpMatriculases) {
    this.id = id;
    this.sgpDocumentosBinarios = sgpDocumentosBinarios;
    this.sgpSubareas = sgpSubareas;
    this.dependencia = dependencia;
    this.nombre = nombre;
    this.abreviatura = abreviatura;
    this.titulo = titulo;
    this.nivforId = nivforId;
    this.fechaAprobacionFacultad = fechaAprobacionFacultad;
    this.fechaAprobacionDireccion = fechaAprobacionDireccion;
    this.nroResolucionConsejo = nroResolucionConsejo;
    this.fechaAprobacionConsejo = fechaAprobacionConsejo;
    this.estado = estado;
    this.rolId = rolId;
    this.estaactivo = estaactivo;
    this.creado = creado;
    this.fechaCreacion = fechaCreacion;
    this.actualizado = actualizado;
    this.fechaActualizacion = fechaActualizacion;
    this.sgpTemases = sgpTemases;
    this.sgpPlanesCursos = sgpPlanesCursos;
    this.sgpResolucionesSenescyts = sgpResolucionesSenescyts;
    this.sgpMatriculases = sgpMatriculases;
  }

  public int getId() {
    return this.id;
  }

  public void setId(int id) {
    this.id = id;
  }

  public SgpDocumentosBinarios getSgpDocumentosBinarios() {
    return this.sgpDocumentosBinarios;
  }

  public void setSgpDocumentosBinarios(SgpDocumentosBinarios sgpDocumentosBinarios) {
    this.sgpDocumentosBinarios = sgpDocumentosBinarios;
  }

  public SgpSubareas getSgpSubareas() {
    return this.sgpSubareas;
  }

  public void setSgpSubareas(SgpSubareas sgpSubareas) {
    this.sgpSubareas = sgpSubareas;
  }

  public Dependencias getDependencia() {
    return dependencia;
  }

  public void setDependencia(Dependencias dependencia) {
    this.dependencia = dependencia;
  }

  public String getNombre() {
    return this.nombre;
  }

  public void setNombre(String nombre) {
    this.nombre = nombre;
  }

  public String getAbreviatura() {
    return this.abreviatura;
  }

  public void setAbreviatura(String abreviatura) {
    this.abreviatura = abreviatura;
  }

  public Titulos getTitulo() {
    return titulo;
  }

  public void setTitulo(Titulos titulo) {
    this.titulo = titulo;
  }

  public int getNivforId() {
    return this.nivforId;
  }

  public void setNivforId(int nivforId) {
    this.nivforId = nivforId;
  }

  public Date getFechaAprobacionFacultad() {
    return this.fechaAprobacionFacultad;
  }

  public void setFechaAprobacionFacultad(Date fechaAprobacionFacultad) {
    this.fechaAprobacionFacultad = fechaAprobacionFacultad;
  }

  public Date getFechaAprobacionDireccion() {
    return this.fechaAprobacionDireccion;
  }

  public void setFechaAprobacionDireccion(Date fechaAprobacionDireccion) {
    this.fechaAprobacionDireccion = fechaAprobacionDireccion;
  }

  public String getNroResolucionConsejo() {
    return this.nroResolucionConsejo;
  }

  public void setNroResolucionConsejo(String nroResolucionConsejo) {
    this.nroResolucionConsejo = nroResolucionConsejo;
  }

  public Date getFechaAprobacionConsejo() {
    return this.fechaAprobacionConsejo;
  }

  public void setFechaAprobacionConsejo(Date fechaAprobacionConsejo) {
    this.fechaAprobacionConsejo = fechaAprobacionConsejo;
  }

  public String getEstado() {
    return this.estado;
  }

  public void setEstado(String estado) {
    this.estado = estado;
  }

  public String getRolId() {
    return this.rolId;
  }

  public void setRolId(String rolId) {
    this.rolId = rolId;
  }

  public char getEstaactivo() {
    return this.estaactivo;
  }

  public void setEstaactivo(char estaactivo) {
    this.estaactivo = estaactivo;
  }

  public String getCreado() {
    return this.creado;
  }

  public void setCreado(String creado) {
    this.creado = creado;
  }

  public Date getFechaCreacion() {
    return this.fechaCreacion;
  }

  public void setFechaCreacion(Date fechaCreacion) {
    this.fechaCreacion = fechaCreacion;
  }

  public String getActualizado() {
    return this.actualizado;
  }

  public void setActualizado(String actualizado) {
    this.actualizado = actualizado;
  }

  public Date getFechaActualizacion() {
    return this.fechaActualizacion;
  }

  public void setFechaActualizacion(Date fechaActualizacion) {
    this.fechaActualizacion = fechaActualizacion;
  }

  public Set getSgpTemases() {
    return this.sgpTemases;
  }

  public void setSgpTemases(Set sgpTemases) {
    this.sgpTemases = sgpTemases;
  }

  public Set getSgpPlanesCursos() {
    return this.sgpPlanesCursos;
  }

  public void setSgpPlanesCursos(Set sgpPlanesCursos) {
    this.sgpPlanesCursos = sgpPlanesCursos;
  }

  public Set getSgpResolucionesSenescyts() {
    return this.sgpResolucionesSenescyts;
  }

  public void setSgpResolucionesSenescyts(Set sgpResolucionesSenescyts) {
    this.sgpResolucionesSenescyts = sgpResolucionesSenescyts;
  }

  public Set getSgpMatriculases() {
    return this.sgpMatriculases;
  }

  public void setSgpMatriculases(Set sgpMatriculases) {
    this.sgpMatriculases = sgpMatriculases;
  }

  public String getIdFac() {
    return idFac;
  }

  public void setIdFac(String idFac) {
    this.idFac = idFac;
  }
}
