package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * SgpCursosEstudiantes generated by hbm2java
 */
public class SgpCursosEstudiantes implements java.io.Serializable {

    private SgpCursosEstudiantesId id;
    private SgpEdiciones sgpEdiciones;
    private SgpSecciones sgpSecciones;
    private Integer placurId;
    private Integer mallaId;
    private Integer mencionId;
    private String estado;
    private int perlecId;
    private char tieneBeca;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;

    public SgpCursosEstudiantes() {
    }

    public SgpCursosEstudiantes(SgpCursosEstudiantesId id, SgpEdiciones sgpEdiciones, SgpSecciones sgpSecciones, Integer placurId, Integer mallaId, Integer mencionId, String estado, int perlecId, char tieneBeca, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
        this.id = id;
        this.sgpEdiciones = sgpEdiciones;
        this.sgpSecciones = sgpSecciones;
        this.placurId = placurId;
        this.mallaId = mallaId;
        this.mencionId = mencionId;
        this.estado = estado;
        this.perlecId = perlecId;
        this.tieneBeca = tieneBeca;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
    }

    public String getActualizado() {
        return actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public String getCreado() {
        return creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public char getEstaactivo() {
        return estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getEstado() {
        return estado;
    }

    public void setEstado(String estado) {
        this.estado = estado;
    }

    public Date getFechaActualizacion() {
        return fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Date getFechaCreacion() {
        return fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public SgpCursosEstudiantesId getId() {
        return id;
    }

    public void setId(SgpCursosEstudiantesId id) {
        this.id = id;
    }

    public Integer getMallaId() {
        return mallaId;
    }

    public void setMallaId(Integer mallaId) {
        this.mallaId = mallaId;
    }

    public Integer getMencionId() {
        return mencionId;
    }

    public void setMencionId(Integer mencionId) {
        this.mencionId = mencionId;
    }

    public int getPerlecId() {
        return perlecId;
    }

    public void setPerlecId(int perlecId) {
        this.perlecId = perlecId;
    }

    public Integer getPlacurId() {
        return placurId;
    }

    public void setPlacurId(Integer placurId) {
        this.placurId = placurId;
    }

    public SgpEdiciones getSgpEdiciones() {
        return sgpEdiciones;
    }

    public void setSgpEdiciones(SgpEdiciones sgpEdiciones) {
        this.sgpEdiciones = sgpEdiciones;
    }

    public SgpSecciones getSgpSecciones() {
        return sgpSecciones;
    }

    public void setSgpSecciones(SgpSecciones sgpSecciones) {
        this.sgpSecciones = sgpSecciones;
    }

    public char getTieneBeca() {
        return tieneBeca;
    }

    public void setTieneBeca(char tieneBeca) {
        this.tieneBeca = tieneBeca;
    }
}
