package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

/**
 * SgpCursosEstudiantesId generated by hbm2java
 */
public class SgpCursosEstudiantesId implements java.io.Serializable {

    private int id;
    private String personaId;

    public SgpCursosEstudiantesId() {
    }

    public SgpCursosEstudiantesId(int id, String personaId) {
        this.id = id;
        this.personaId = personaId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getPersonaId() {
        return this.personaId;
    }

    public void setPersonaId(String personaId) {
        this.personaId = personaId;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final SgpCursosEstudiantesId other = (SgpCursosEstudiantesId) obj;
        if (this.id != other.id) {
            return false;
        }
        if ((this.personaId == null) ? (other.personaId != null) : !this.personaId.equals(other.personaId)) {
            return false;
        }
        return true;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 83 * hash + this.id;
        hash = 83 * hash + (this.personaId != null ? this.personaId.hashCode() : 0);
        return hash;
    }
}
