package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpComponentesDetalles generated by hbm2java
 */
public class SgpComponentesDetalles  implements java.io.Serializable {


     private SgpComponentesDetallesId id;
     private SgpComponentesCabeceras sgpComponentesCabeceras;
     private SgpComponentes sgpComponentes;
     private String numero;
     private short orden;
     private char publicable;
     private char automatico;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set sgpComponentesPlaneses = new HashSet(0);

    public SgpComponentesDetalles() {
    }

	
    public SgpComponentesDetalles(SgpComponentesDetallesId id, SgpComponentesCabeceras sgpComponentesCabeceras, SgpComponentes sgpComponentes, short orden, char publicable, char automatico, char estaactivo, String creado) {
        this.id = id;
        this.sgpComponentesCabeceras = sgpComponentesCabeceras;
        this.sgpComponentes = sgpComponentes;
        this.orden = orden;
        this.publicable = publicable;
        this.automatico = automatico;
        this.estaactivo = estaactivo;
        this.creado = creado;
    }
    public SgpComponentesDetalles(SgpComponentesDetallesId id, SgpComponentesCabeceras sgpComponentesCabeceras, SgpComponentes sgpComponentes, String numero, short orden, char publicable, char automatico, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpComponentesPlaneses) {
       this.id = id;
       this.sgpComponentesCabeceras = sgpComponentesCabeceras;
       this.sgpComponentes = sgpComponentes;
       this.numero = numero;
       this.orden = orden;
       this.publicable = publicable;
       this.automatico = automatico;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpComponentesPlaneses = sgpComponentesPlaneses;
    }
   
    public SgpComponentesDetallesId getId() {
        return this.id;
    }
    
    public void setId(SgpComponentesDetallesId id) {
        this.id = id;
    }
    public SgpComponentesCabeceras getSgpComponentesCabeceras() {
        return this.sgpComponentesCabeceras;
    }
    
    public void setSgpComponentesCabeceras(SgpComponentesCabeceras sgpComponentesCabeceras) {
        this.sgpComponentesCabeceras = sgpComponentesCabeceras;
    }
    public SgpComponentes getSgpComponentes() {
        return this.sgpComponentes;
    }
    
    public void setSgpComponentes(SgpComponentes sgpComponentes) {
        this.sgpComponentes = sgpComponentes;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public short getOrden() {
        return this.orden;
    }
    
    public void setOrden(short orden) {
        this.orden = orden;
    }
    public char getPublicable() {
        return this.publicable;
    }
    
    public void setPublicable(char publicable) {
        this.publicable = publicable;
    }
    public char getAutomatico() {
        return this.automatico;
    }
    
    public void setAutomatico(char automatico) {
        this.automatico = automatico;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getSgpComponentesPlaneses() {
        return this.sgpComponentesPlaneses;
    }
    
    public void setSgpComponentesPlaneses(Set sgpComponentesPlaneses) {
        this.sgpComponentesPlaneses = sgpComponentesPlaneses;
    }




}


