package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpComponentesPlanesId generated by hbm2java
 */
public class SgpComponentesPlanesId  implements java.io.Serializable {


     private int curposId;
     private int placurId;
     private int cabcomId;
     private int componenteId;

    public SgpComponentesPlanesId() {
    }

    public SgpComponentesPlanesId(int curposId, int placurId, int cabcomId, int componenteId) {
       this.curposId = curposId;
       this.placurId = placurId;
       this.cabcomId = cabcomId;
       this.componenteId = componenteId;
    }
   
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getPlacurId() {
        return this.placurId;
    }
    
    public void setPlacurId(int placurId) {
        this.placurId = placurId;
    }
    public int getCabcomId() {
        return this.cabcomId;
    }
    
    public void setCabcomId(int cabcomId) {
        this.cabcomId = cabcomId;
    }
    public int getComponenteId() {
        return this.componenteId;
    }
    
    public void setComponenteId(int componenteId) {
        this.componenteId = componenteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpComponentesPlanesId) ) return false;
		 SgpComponentesPlanesId castOther = ( SgpComponentesPlanesId ) other; 
         
		 return (this.getCurposId()==castOther.getCurposId())
 && (this.getPlacurId()==castOther.getPlacurId())
 && (this.getCabcomId()==castOther.getCabcomId())
 && (this.getComponenteId()==castOther.getComponenteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getPlacurId();
         result = 37 * result + this.getCabcomId();
         result = 37 * result + this.getComponenteId();
         return result;
   }   


}


