package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * SgpDirectoresCurso generated by hbm2java
 */
public class SgpDirectoresCurso implements java.io.Serializable {

    private int id;
    private SgpEdiciones sgpEdiciones;
    private String personaId;
    private String titulo;
    private char encargado;
    private char enFuncion;
    private Date fechaFinaliza;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private Date fechaInicia;
    /*
     * CAMPOS ADICIONALES
     */
    private String nombres;
    private String apellidos;
    private String identificacion;
    private Boolean estaGuardado;
    private Boolean esEditar;
    private boolean selected;
    private String tipoFuncion;
    private String estaEnFuncion;
    private String fechaIniciaStr = "";
    private String fechaFinalizaStr = "";

    public SgpDirectoresCurso() {
    }

    public SgpDirectoresCurso(int id, SgpEdiciones sgpEdiciones, String personaId, String titulo, char encargado, char enFuncion, char estaactivo, String creado, Date fechaCreacion, Date fechaInicia) {
        this.id = id;
        this.sgpEdiciones = sgpEdiciones;
        this.personaId = personaId;
        this.titulo = titulo;
        this.encargado = encargado;
        this.enFuncion = enFuncion;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.fechaInicia = fechaInicia;
    }

    public SgpDirectoresCurso(int id, SgpEdiciones sgpEdiciones, String personaId, String titulo, char encargado, char enFuncion, Date fechaFinaliza, Date fechaInicia, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
        this.id = id;
        this.sgpEdiciones = sgpEdiciones;
        this.personaId = personaId;
        this.titulo = titulo;
        this.encargado = encargado;
        this.enFuncion = enFuncion;
        this.fechaFinaliza = fechaFinaliza;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.fechaInicia = fechaInicia;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public SgpEdiciones getSgpEdiciones() {
        return this.sgpEdiciones;
    }

    public void setSgpEdiciones(SgpEdiciones sgpEdiciones) {
        this.sgpEdiciones = sgpEdiciones;
    }

    public String getPersonaId() {
        return this.personaId;
    }

    public void setPersonaId(String personaId) {
        this.personaId = personaId;
    }

    public String getTitulo() {
        return this.titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public char getEncargado() {
        return this.encargado;
    }

    public void setEncargado(char encargado) {
        this.encargado = encargado;
    }

    public char getEnFuncion() {
        return this.enFuncion;
    }

    public void setEnFuncion(char enFuncion) {
        this.enFuncion = enFuncion;
    }

    public Date getFechaFinaliza() {
        return this.fechaFinaliza;
    }

    public void setFechaFinaliza(Date fechaFinaliza) {
        this.fechaFinaliza = fechaFinaliza;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Date getFechaInicia() {
        return fechaInicia;
    }

    public void setFechaInicia(Date fechaInicia) {
        this.fechaInicia = fechaInicia;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public Boolean getEstaGuardado() {
        return estaGuardado;
    }

    public void setEstaGuardado(Boolean estaGuardado) {
        this.estaGuardado = estaGuardado;
    }

    public Boolean getEsEditar() {
        return esEditar;
    }

    public void setEsEditar(Boolean esEditar) {
        this.esEditar = esEditar;
    }
    

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public String getEstaEnFuncion() {
        return estaEnFuncion;
    }

    public void setEstaEnFuncion(String estaEnFuncion) {
        this.estaEnFuncion = estaEnFuncion;
    }

    public String getTipoFuncion() {
        return tipoFuncion;
    }

    public void setTipoFuncion(String tipoFuncion) {
        this.tipoFuncion = tipoFuncion;
    }

    public String getFechaFinalizaStr() {
        return fechaFinalizaStr;
    }

    public void setFechaFinalizaStr(String fechaFinalizaStr) {
        this.fechaFinalizaStr = fechaFinalizaStr;
    }

    public String getFechaIniciaStr() {
        return fechaIniciaStr;
    }

    public void setFechaIniciaStr(String fechaIniciaStr) {
        this.fechaIniciaStr = fechaIniciaStr;
    }
    
}
