package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpDocumentosAutorizacion generated by hbm2java
 */
public class SgpDocumentosAutorizacion  implements java.io.Serializable {


     private int id;
     private SgpTiposProcesos sgpTiposProcesos;
     private SgpMatriculasAsignaturas sgpMatriculasAsignaturas;
     private String numeroDocumento;
     private String autorizado;
     private Date fechaAutorizacion;
     private String observacion;
     private String referencia;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpDocumentosAutorizacion() {
    }

	
    public SgpDocumentosAutorizacion(int id, SgpTiposProcesos sgpTiposProcesos, SgpMatriculasAsignaturas sgpMatriculasAsignaturas, String numeroDocumento, String autorizado, Date fechaAutorizacion, String referencia, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpTiposProcesos = sgpTiposProcesos;
        this.sgpMatriculasAsignaturas = sgpMatriculasAsignaturas;
        this.numeroDocumento = numeroDocumento;
        this.autorizado = autorizado;
        this.fechaAutorizacion = fechaAutorizacion;
        this.referencia = referencia;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpDocumentosAutorizacion(int id, SgpTiposProcesos sgpTiposProcesos, SgpMatriculasAsignaturas sgpMatriculasAsignaturas, String numeroDocumento, String autorizado, Date fechaAutorizacion, String observacion, String referencia, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpTiposProcesos = sgpTiposProcesos;
       this.sgpMatriculasAsignaturas = sgpMatriculasAsignaturas;
       this.numeroDocumento = numeroDocumento;
       this.autorizado = autorizado;
       this.fechaAutorizacion = fechaAutorizacion;
       this.observacion = observacion;
       this.referencia = referencia;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public SgpTiposProcesos getSgpTiposProcesos() {
        return this.sgpTiposProcesos;
    }
    
    public void setSgpTiposProcesos(SgpTiposProcesos sgpTiposProcesos) {
        this.sgpTiposProcesos = sgpTiposProcesos;
    }
    public SgpMatriculasAsignaturas getSgpMatriculasAsignaturas() {
        return this.sgpMatriculasAsignaturas;
    }
    
    public void setSgpMatriculasAsignaturas(SgpMatriculasAsignaturas sgpMatriculasAsignaturas) {
        this.sgpMatriculasAsignaturas = sgpMatriculasAsignaturas;
    }
    public String getNumeroDocumento() {
        return this.numeroDocumento;
    }
    
    public void setNumeroDocumento(String numeroDocumento) {
        this.numeroDocumento = numeroDocumento;
    }
    public String getAutorizado() {
        return this.autorizado;
    }
    
    public void setAutorizado(String autorizado) {
        this.autorizado = autorizado;
    }
    public Date getFechaAutorizacion() {
        return this.fechaAutorizacion;
    }
    
    public void setFechaAutorizacion(Date fechaAutorizacion) {
        this.fechaAutorizacion = fechaAutorizacion;
    }
    public String getObservacion() {
        return this.observacion;
    }
    
    public void setObservacion(String observacion) {
        this.observacion = observacion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


