package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpDocentesAsignaturas generated by hbm2java
 */
public class SgpDocentesAsignaturas  implements java.io.Serializable {


     private SgpDocentesAsignaturasId id;
     private SgpAsignaturasMallas sgpAsignaturasMallas;
     private String titulo;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpDocentesAsignaturas() {
    }

	
    public SgpDocentesAsignaturas(SgpDocentesAsignaturasId id, SgpAsignaturasMallas sgpAsignaturasMallas, String titulo, char estaactivo, String creado) {
        this.id = id;
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
        this.titulo = titulo;
        this.estaactivo = estaactivo;
        this.creado = creado;
    }
    public SgpDocentesAsignaturas(SgpDocentesAsignaturasId id, SgpAsignaturasMallas sgpAsignaturasMallas, String titulo, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpAsignaturasMallas = sgpAsignaturasMallas;
       this.titulo = titulo;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public SgpDocentesAsignaturasId getId() {
        return this.id;
    }
    
    public void setId(SgpDocentesAsignaturasId id) {
        this.id = id;
    }
    public SgpAsignaturasMallas getSgpAsignaturasMallas() {
        return this.sgpAsignaturasMallas;
    }
    
    public void setSgpAsignaturasMallas(SgpAsignaturasMallas sgpAsignaturasMallas) {
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


