package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpEquivalencias generated by hbm2java
 */
public class SgpEquivalencias  implements java.io.Serializable {


     private short id;
     private String nombre;
     private String abreviatura;
     private BigDecimal notaInicial;
     private BigDecimal notaFinal;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set sgpMatriculasAsignaturases = new HashSet(0);

    public SgpEquivalencias() {
    }

	
    public SgpEquivalencias(short id, String nombre, String abreviatura, BigDecimal notaInicial, BigDecimal notaFinal, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.abreviatura = abreviatura;
        this.notaInicial = notaInicial;
        this.notaFinal = notaFinal;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpEquivalencias(short id, String nombre, String abreviatura, BigDecimal notaInicial, BigDecimal notaFinal, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpMatriculasAsignaturases) {
       this.id = id;
       this.nombre = nombre;
       this.abreviatura = abreviatura;
       this.notaInicial = notaInicial;
       this.notaFinal = notaFinal;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpMatriculasAsignaturases = sgpMatriculasAsignaturases;
    }
   
    public short getId() {
        return this.id;
    }
    
    public void setId(short id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public BigDecimal getNotaInicial() {
        return this.notaInicial;
    }
    
    public void setNotaInicial(BigDecimal notaInicial) {
        this.notaInicial = notaInicial;
    }
    public BigDecimal getNotaFinal() {
        return this.notaFinal;
    }
    
    public void setNotaFinal(BigDecimal notaFinal) {
        this.notaFinal = notaFinal;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getSgpMatriculasAsignaturases() {
        return this.sgpMatriculasAsignaturases;
    }
    
    public void setSgpMatriculasAsignaturases(Set sgpMatriculasAsignaturases) {
        this.sgpMatriculasAsignaturases = sgpMatriculasAsignaturases;
    }




}


