package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpFormasEvaluacion generated by hbm2java
 */
public class SgpFormasEvaluacion  implements java.io.Serializable {


     private int id;
     private String nombre;
     private String descripcion;
     private byte numeroAportes;
     private BigDecimal minimoAprobar;
     private String tipoCalificacion;
     private int faltasPermitidas;
     private BigDecimal maximaCalificacion;
     private byte nroDecimales;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private String abreviatura;
     private String enVigencia;
     private String enUso;
     private Set sgpRegistrosCabecerases = new HashSet(0);
     private Set sgpAsignaturasMallases = new HashSet(0);
     private Set sgpEvaluacionesAporteses = new HashSet(0);
     private Set sgpEvaluacionesEstadoses = new HashSet(0);
     private Set sgpMallases = new HashSet(0);

    public SgpFormasEvaluacion() {
    }

	
    public SgpFormasEvaluacion(int id, String nombre, String descripcion, byte numeroAportes, String tipoCalificacion, int faltasPermitidas, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.descripcion = descripcion;
        this.numeroAportes = numeroAportes;
        this.tipoCalificacion = tipoCalificacion;
        this.faltasPermitidas = faltasPermitidas;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpFormasEvaluacion(int id, String nombre, String descripcion, byte numeroAportes, BigDecimal minimoAprobar, String tipoCalificacion, int faltasPermitidas, BigDecimal maximaCalificacion, byte nroDecimales, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpRegistrosCabecerases, Set sgpAsignaturasMallases, Set sgpEvaluacionesAporteses, Set sgpEvaluacionesEstadoses, Set sgpMallases) {
       this.id = id;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.numeroAportes = numeroAportes;
       this.minimoAprobar = minimoAprobar;
       this.tipoCalificacion = tipoCalificacion;
       this.faltasPermitidas = faltasPermitidas;
       this.maximaCalificacion = maximaCalificacion;
       this.nroDecimales = nroDecimales;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpRegistrosCabecerases = sgpRegistrosCabecerases;
       this.sgpAsignaturasMallases = sgpAsignaturasMallases;
       this.sgpEvaluacionesAporteses = sgpEvaluacionesAporteses;
       this.sgpEvaluacionesEstadoses = sgpEvaluacionesEstadoses;
       this.sgpMallases = sgpMallases;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public byte getNumeroAportes() {
        return this.numeroAportes;
    }
    
    public void setNumeroAportes(byte numeroAportes) {
        this.numeroAportes = numeroAportes;
    }
    public BigDecimal getMinimoAprobar() {
        return this.minimoAprobar;
    }
    
    public void setMinimoAprobar(BigDecimal minimoAprobar) {
        this.minimoAprobar = minimoAprobar;
    }
    public String getTipoCalificacion() {
        return this.tipoCalificacion;
    }
    
    public void setTipoCalificacion(String tipoCalificacion) {
        this.tipoCalificacion = tipoCalificacion;
    }
    public int getFaltasPermitidas() {
        return this.faltasPermitidas;
    }
    
    public void setFaltasPermitidas(int faltasPermitidas) {
        this.faltasPermitidas = faltasPermitidas;
    }
    public BigDecimal getMaximaCalificacion() {
        return this.maximaCalificacion;
    }
    
    public void setMaximaCalificacion(BigDecimal maximaCalificacion) {
        this.maximaCalificacion = maximaCalificacion;
    }
    public byte getNroDecimales() {
        return this.nroDecimales;
    }
    
    public void setNroDecimales(byte nroDecimales) {
        this.nroDecimales = nroDecimales;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public String getEnVigencia() {
        return this.enVigencia;
    }
    
    public void setEnVigencia(String enVigencia) {
        this.enVigencia = enVigencia;
    }
    public String getEnUso() {
        return this.enUso;
    }
    
    public void setEnUso(String enUso) {
        this.enUso = enUso;
    }
    
    public Set getSgpRegistrosCabecerases() {
        return this.sgpRegistrosCabecerases;
    }
    
    public void setSgpRegistrosCabecerases(Set sgpRegistrosCabecerases) {
        this.sgpRegistrosCabecerases = sgpRegistrosCabecerases;
    }
    public Set getSgpAsignaturasMallases() {
        return this.sgpAsignaturasMallases;
    }
    
    public void setSgpAsignaturasMallases(Set sgpAsignaturasMallases) {
        this.sgpAsignaturasMallases = sgpAsignaturasMallases;
    }
    public Set getSgpEvaluacionesAporteses() {
        return this.sgpEvaluacionesAporteses;
    }
    
    public void setSgpEvaluacionesAporteses(Set sgpEvaluacionesAporteses) {
        this.sgpEvaluacionesAporteses = sgpEvaluacionesAporteses;
    }
    public Set getSgpEvaluacionesEstadoses() {
        return this.sgpEvaluacionesEstadoses;
    }
    
    public void setSgpEvaluacionesEstadoses(Set sgpEvaluacionesEstadoses) {
        this.sgpEvaluacionesEstadoses = sgpEvaluacionesEstadoses;
    }
    public Set getSgpMallases() {
        return this.sgpMallases;
    }
    
    public void setSgpMallases(Set sgpMallases) {
        this.sgpMallases = sgpMallases;
    }




}


