package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpHorariosDocentes generated by hbm2java
 */
public class SgpHorariosDocentes  implements java.io.Serializable {


     private SgpHorariosDocentesId id;
     private SgpHorariosOfertas sgpHorariosOfertas;
     private String personaId;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizado;
     private Character marcaAsistencia;
     /*CAMPOS PARA VISUALIZAR NOMBRES DE DOCENTES*/
     private String nombres;
     private String apellidos;
     private String identificacion;
     private Boolean estaGuardado = false;
     private String asistencia="";
     private boolean _selected = false;

    public SgpHorariosDocentes() {
    }

	
    public SgpHorariosDocentes(SgpHorariosDocentesId id, SgpHorariosOfertas sgpHorariosOfertas, String personaId, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpHorariosOfertas = sgpHorariosOfertas;
        this.personaId = personaId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpHorariosDocentes(SgpHorariosDocentesId id, SgpHorariosOfertas sgpHorariosOfertas, String personaId, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizado, Character marcaAsistencia) {
       this.id = id;
       this.sgpHorariosOfertas = sgpHorariosOfertas;
       this.personaId = personaId;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizado = fechaActualizado;
       this.marcaAsistencia = marcaAsistencia;
    }
   
    public SgpHorariosDocentesId getId() {
        return this.id;
    }
    
    public void setId(SgpHorariosDocentesId id) {
        this.id = id;
    }
    public SgpHorariosOfertas getSgpHorariosOfertas() {
        return this.sgpHorariosOfertas;
    }
    
    public void setSgpHorariosOfertas(SgpHorariosOfertas sgpHorariosOfertas) {
        this.sgpHorariosOfertas = sgpHorariosOfertas;
    }
    public String getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(String personaId) {
        this.personaId = personaId;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizado() {
        return this.fechaActualizado;
    }
    
    public void setFechaActualizado(Date fechaActualizado) {
        this.fechaActualizado = fechaActualizado;
    }
    public Character getMarcaAsistencia() {
        return this.marcaAsistencia;
    }
    
    public void setMarcaAsistencia(Character marcaAsistencia) {
        this.marcaAsistencia = marcaAsistencia;
    }

    public String getApellidos() {
        return apellidos;
    }

    public void setApellidos(String apellidos) {
        this.apellidos = apellidos;
    }

    public String getNombres() {
        return nombres;
    }

    public void setNombres(String nombres) {
        this.nombres = nombres;
    }

    public String getIdentificacion() {
        return identificacion;
    }

    public void setIdentificacion(String identificacion) {
        this.identificacion = identificacion;
    }

    public Boolean getEstaGuardado() {
        return estaGuardado;
    }

    public void setEstaGuardado(Boolean estaGuardado) {
        this.estaGuardado = estaGuardado;
    }

    public String getAsistencia() {
        return asistencia;
    }

    public void setAsistencia(String asistencia) {
        this.asistencia = asistencia;
    }

    public boolean isSelected() {
        return _selected;
    }

    public void setSelected(boolean _selected) {
        this._selected = _selected;
    }

    



}


