package datos.pojos.sgap;
// Generated 24/01/2014 11:30:34 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpInstitucionesJuridicasId generated by hbm2java
 */
public class SgpInstitucionesJuridicasId  implements java.io.Serializable {


     private int curposId;
     private int placurId;
     private String institucionId;

    public SgpInstitucionesJuridicasId() {
    }

    public SgpInstitucionesJuridicasId(int curposId, int placurId, String institucionId) {
       this.curposId = curposId;
       this.placurId = placurId;
       this.institucionId = institucionId;
    }
   
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getPlacurId() {
        return this.placurId;
    }
    
    public void setPlacurId(int placurId) {
        this.placurId = placurId;
    }
    public String getInstitucionId() {
        return this.institucionId;
    }
    
    public void setInstitucionId(String institucionId) {
        this.institucionId = institucionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpInstitucionesJuridicasId) ) return false;
		 SgpInstitucionesJuridicasId castOther = ( SgpInstitucionesJuridicasId ) other; 
         
		 return (this.getCurposId()==castOther.getCurposId())
 && (this.getPlacurId()==castOther.getPlacurId())
 && ( (this.getInstitucionId()==castOther.getInstitucionId()) || ( this.getInstitucionId()!=null && castOther.getInstitucionId()!=null && this.getInstitucionId().equals(castOther.getInstitucionId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getPlacurId();
         result = 37 * result + ( getInstitucionId() == null ? 0 : this.getInstitucionId().hashCode() );
         return result;
   }   


}


