package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpInscripcionesId generated by hbm2java
 */
public class SgpInscripcionesId  implements java.io.Serializable {


     private String personaId;
     private int curposId;
     private int edicionId;
     private int perlecId;

    public SgpInscripcionesId() {
    }

    public SgpInscripcionesId(String personaId, int curposId, int edicionId, int perlecId) {
       this.personaId = personaId;
       this.curposId = curposId;
       this.edicionId = edicionId;
       this.perlecId = perlecId;
    }
   
    public String getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(String personaId) {
        this.personaId = personaId;
    }
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }
    public int getPerlecId() {
        return this.perlecId;
    }
    
    public void setPerlecId(int perlecId) {
        this.perlecId = perlecId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpInscripcionesId) ) return false;
		 SgpInscripcionesId castOther = ( SgpInscripcionesId ) other; 
         
		 return ( (this.getPersonaId()==castOther.getPersonaId()) || ( this.getPersonaId()!=null && castOther.getPersonaId()!=null && this.getPersonaId().equals(castOther.getPersonaId()) ) )
 && (this.getCurposId()==castOther.getCurposId())
 && (this.getEdicionId()==castOther.getEdicionId())
 && (this.getPerlecId()==castOther.getPerlecId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getPersonaId() == null ? 0 : this.getPersonaId().hashCode() );
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getEdicionId();
         result = 37 * result + this.getPerlecId();
         return result;
   }   


}


