package datos.pojos.sgap;
// Generated 30/01/2014 07:52:14 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * SgpLineasInvestigacion generated by hbm2java
 */
public class SgpLineasInvestigacion implements java.io.Serializable {

    private int id;
    private SgpPlanesCurso sgpPlanesCurso;
    private Integer lineaId;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private int areaId;
    //otro 
    private boolean _guardado = false;
    private String arealbl = "";
    private String linealbl = "";
    private boolean _selected=false;

    public SgpLineasInvestigacion() {
    }

    public SgpLineasInvestigacion(int id, SgpPlanesCurso sgpPlanesCurso, char estaactivo, String creado, Date fechaCreacion, int areaId) {
        this.id = id;
        this.sgpPlanesCurso = sgpPlanesCurso;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.areaId = areaId;
    }

    public SgpLineasInvestigacion(int id, SgpPlanesCurso sgpPlanesCurso, Integer lineaId, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, int areaId) {
        this.id = id;
        this.sgpPlanesCurso = sgpPlanesCurso;
        this.lineaId = lineaId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.areaId = areaId;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public SgpPlanesCurso getSgpPlanesCurso() {
        return this.sgpPlanesCurso;
    }

    public void setSgpPlanesCurso(SgpPlanesCurso sgpPlanesCurso) {
        this.sgpPlanesCurso = sgpPlanesCurso;
    }

    public Integer getLineaId() {
        return this.lineaId;
    }

    public void setLineaId(Integer lineaId) {
        this.lineaId = lineaId;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public int getAreaId() {
        return this.areaId;
    }

    public void setAreaId(int areaId) {
        this.areaId = areaId;
    }

    public boolean isGuardado() {
        return _guardado;
    }

    public void setGuardado(boolean _guardado) {
        this._guardado = _guardado;
    }

    public String getArealbl() {
        return arealbl;
    }

    public void setArealbl(String arealbl) {
        this.arealbl = arealbl;
    }

    public String getLinealbl() {
        return linealbl;
    }

    public void setLinealbl(String linealbl) {
        this.linealbl = linealbl;
    }

    public boolean isSelected() {
        return _selected;
    }

    public void setSelected(boolean _selected) {
        this._selected = _selected;
    }

    
}
