package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpMatriculasId generated by hbm2java
 */
public class SgpMatriculasId  implements java.io.Serializable {


     private int curposId;
     private int edicionId;
     private String personaId;

    public SgpMatriculasId() {
    }

    public SgpMatriculasId(int curposId, int edicionId, String personaId) {
       this.curposId = curposId;
       this.edicionId = edicionId;
       this.personaId = personaId;
    }
   
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }
    public String getPersonaId() {
        return this.personaId;
    }
    
    public void setPersonaId(String personaId) {
        this.personaId = personaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpMatriculasId) ) return false;
		 SgpMatriculasId castOther = ( SgpMatriculasId ) other; 
         
		 return (this.getCurposId()==castOther.getCurposId())
 && (this.getEdicionId()==castOther.getEdicionId())
 && ( (this.getPersonaId()==castOther.getPersonaId()) || ( this.getPersonaId()!=null && castOther.getPersonaId()!=null && this.getPersonaId().equals(castOther.getPersonaId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getEdicionId();
         result = 37 * result + ( getPersonaId() == null ? 0 : this.getPersonaId().hashCode() );
         return result;
   }   


}


