package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;

/**
 * SgpMencionesAsignaturas generated by hbm2java
 */
public class SgpMencionesAsignaturas implements java.io.Serializable {

    private SgpMencionesAsignaturasId id;
    private SgpMenciones sgpMenciones;
    private SgpAsignaturasMallas sgpAsignaturasMallas;
    private SgpUnidadesOrganizacion sgpUnidadesOrganizacion;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private String esobligatoria;
    private String eselectiva;

    public SgpMencionesAsignaturas() {
    }

    public SgpMencionesAsignaturas(SgpMencionesAsignaturasId id, SgpMenciones sgpMenciones, SgpAsignaturasMallas sgpAsignaturasMallas, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpMenciones = sgpMenciones;
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpMencionesAsignaturas(SgpMencionesAsignaturasId id, SgpMenciones sgpMenciones, SgpAsignaturasMallas sgpAsignaturasMallas, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
        this.id = id;
        this.sgpMenciones = sgpMenciones;
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
    }

    public SgpMencionesAsignaturasId getId() {
        return this.id;
    }

    public void setId(SgpMencionesAsignaturasId id) {
        this.id = id;
    }

    public SgpMenciones getSgpMenciones() {
        return this.sgpMenciones;
    }

    public void setSgpMenciones(SgpMenciones sgpMenciones) {
        this.sgpMenciones = sgpMenciones;
    }

    public SgpAsignaturasMallas getSgpAsignaturasMallas() {
        return this.sgpAsignaturasMallas;
    }

    public void setSgpAsignaturasMallas(SgpAsignaturasMallas sgpAsignaturasMallas) {
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public SgpUnidadesOrganizacion getSgpUnidadesOrganizacion() {
        return sgpUnidadesOrganizacion;
    }

    public void setSgpUnidadesOrganizacion(SgpUnidadesOrganizacion sgpUnidadesOrganizacion) {
        this.sgpUnidadesOrganizacion = sgpUnidadesOrganizacion;
    }

    public String getEsobligatoria() {
        return esobligatoria;
    }

    public void setEsobligatoria(String esobligatoria) {
        this.esobligatoria = esobligatoria;
    }

    public String getEselectiva() {
        return eselectiva;
    }

    public void setEselectiva(String eselectiva) {
        this.eselectiva = eselectiva;
    }
}
