package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpMallas generated by hbm2java
 */
public class SgpMallas  implements java.io.Serializable {


     private SgpMallasId id;
     private SgpFormasEvaluacion sgpFormasEvaluacion;
     private SgpPlanesCurso sgpPlanesCurso;
     private String nombre;
     private char envigencia;
     private char estaactivo;
     private String creado;
     private Date fechacreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set sgpMencioneses = new HashSet(0);
     private Set sgpAsignaturasMallases = new HashSet(0);
     private Set sgpEdicioneses = new HashSet(0);
     private Set sgpUnidadesMallas = new HashSet(0);

    public SgpMallas() {
    }

    public SgpMallas(SgpMallasId id) {
        this.id = id;
    }

    
	
    public SgpMallas(SgpMallasId id, SgpFormasEvaluacion sgpFormasEvaluacion, SgpPlanesCurso sgpPlanesCurso, String nombre, char envigencia, char estaactivo, String creado, Date fechacreacion) {
        this.id = id;
        this.sgpFormasEvaluacion = sgpFormasEvaluacion;
        this.sgpPlanesCurso = sgpPlanesCurso;
        this.nombre = nombre;
        this.envigencia = envigencia;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechacreacion = fechacreacion;
    }
    public SgpMallas(SgpMallasId id, SgpFormasEvaluacion sgpFormasEvaluacion, SgpPlanesCurso sgpPlanesCurso, String nombre, char envigencia, char estaactivo, String creado, Date fechacreacion, String actualizado, Date fechaActualizacion, Set sgpMencioneses, Set sgpAsignaturasMallases, Set sgpEdicioneses) {
       this.id = id;
       this.sgpFormasEvaluacion = sgpFormasEvaluacion;
       this.sgpPlanesCurso = sgpPlanesCurso;
       this.nombre = nombre;
       this.envigencia = envigencia;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechacreacion = fechacreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpMencioneses = sgpMencioneses;
       this.sgpAsignaturasMallases = sgpAsignaturasMallases;
       this.sgpEdicioneses = sgpEdicioneses;
    }
   
    public SgpMallasId getId() {
        return this.id;
    }
    
    public void setId(SgpMallasId id) {
        this.id = id;
    }
    public SgpFormasEvaluacion getSgpFormasEvaluacion() {
        return this.sgpFormasEvaluacion;
    }
    
    public void setSgpFormasEvaluacion(SgpFormasEvaluacion sgpFormasEvaluacion) {
        this.sgpFormasEvaluacion = sgpFormasEvaluacion;
    }
    public SgpPlanesCurso getSgpPlanesCurso() {
        return this.sgpPlanesCurso;
    }
    
    public void setSgpPlanesCurso(SgpPlanesCurso sgpPlanesCurso) {
        this.sgpPlanesCurso = sgpPlanesCurso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public char getEnvigencia() {
        return this.envigencia;
    }
    
    public void setEnvigencia(char envigencia) {
        this.envigencia = envigencia;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechacreacion() {
        return this.fechacreacion;
    }
    
    public void setFechacreacion(Date fechacreacion) {
        this.fechacreacion = fechacreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getSgpMencioneses() {
        return this.sgpMencioneses;
    }
    
    public void setSgpMencioneses(Set sgpMencioneses) {
        this.sgpMencioneses = sgpMencioneses;
    }
    public Set getSgpAsignaturasMallases() {
        return this.sgpAsignaturasMallases;
    }
    
    public void setSgpAsignaturasMallases(Set sgpAsignaturasMallases) {
        this.sgpAsignaturasMallases = sgpAsignaturasMallases;
    }
    public Set getSgpEdicioneses() {
        return this.sgpEdicioneses;
    }
    
    public void setSgpEdicioneses(Set sgpEdicioneses) {
        this.sgpEdicioneses = sgpEdicioneses;
    }

    public Set getSgpUnidadesMallas() {
        return sgpUnidadesMallas;
    }

    public void setSgpUnidadesMallas(Set sgpUnidadesMallas) {
        this.sgpUnidadesMallas = sgpUnidadesMallas;
    }
    




}


