package datos.pojos.sgap;
// Generated 14-mar-2014 11:33:11 by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpOfertaAsignatura generated by hbm2java
 */
public class SgpOfertaAsignatura  implements java.io.Serializable {


     private SgpOfertaAsignaturaId id;
     private Integer sgpTemas;
     private SgpEdiciones sgpEdiciones;
     private SgpAsignaturas sgpAsignaturas;
     private SgpSecciones sgpSecciones;
     private int perlecId;
     private String nombreGrupo;
     private int cupoMin;
     private int cupoMax;
     private int cupoExterno;
     private Integer horasPresenciales;
     private Integer horasEstudiante;
     private Double totalCreditos;
     private int forevaId;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Date fechaInicia;
     private Date fechaTermina;
     private Set sgpOfertaDocenteses = new HashSet(0);
     private Set sgpHorariosOfertases = new HashSet(0);
     /*row Selector*/
     private boolean selected;
     private String nombreTema="";
     private Date fechaIniciaCalificaciones;
     private Date fechaTerminaCalificaciones;

    public SgpOfertaAsignatura() {
    }

	
    public SgpOfertaAsignatura(SgpOfertaAsignaturaId id, Integer sgpTemas, SgpEdiciones sgpEdiciones, SgpAsignaturas sgpAsignaturas, SgpSecciones sgpSecciones, int perlecId, int cupoMin, int cupoMax, int cupoExterno, int forevaId, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpTemas = sgpTemas;
        this.sgpEdiciones = sgpEdiciones;
        this.sgpAsignaturas = sgpAsignaturas;
        this.sgpSecciones = sgpSecciones;
        this.perlecId = perlecId;
        this.cupoMin = cupoMin;
        this.cupoMax = cupoMax;
        this.cupoExterno = cupoExterno;
        this.forevaId = forevaId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpOfertaAsignatura(SgpOfertaAsignaturaId id, Integer sgpTemas, SgpEdiciones sgpEdiciones, SgpAsignaturas sgpAsignaturas, SgpSecciones sgpSecciones, int perlecId, String nombreGrupo, int cupoMin, int cupoMax, int cupoExterno, Integer horasPresenciales, Integer horasEstudiante, Double totalCreditos, int forevaId, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Date fechaInicia, Date fechaTermina, Set sgpOfertaDocenteses, Set sgpHorariosOfertases, Date fechaIniciaCalificaciones, Date fechaTerminaCalificaciones) {
       this.id = id;
       this.sgpTemas = sgpTemas;
       this.sgpEdiciones = sgpEdiciones;
       this.sgpAsignaturas = sgpAsignaturas;
       this.sgpSecciones = sgpSecciones;
       this.perlecId = perlecId;
       this.nombreGrupo = nombreGrupo;
       this.cupoMin = cupoMin;
       this.cupoMax = cupoMax;
       this.cupoExterno = cupoExterno;
       this.horasPresenciales = horasPresenciales;
       this.horasEstudiante = horasEstudiante;
       this.totalCreditos = totalCreditos;
       this.forevaId = forevaId;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaInicia = fechaInicia;
       this.fechaTermina = fechaTermina;
       this.fechaIniciaCalificaciones = fechaIniciaCalificaciones;
       this.fechaTerminaCalificaciones = fechaTerminaCalificaciones;
    }
    
    public SgpOfertaAsignatura(SgpOfertaAsignaturaId id, Integer sgpTemas, SgpEdiciones sgpEdiciones, SgpAsignaturas sgpAsignaturas, SgpSecciones sgpSecciones, int perlecId, Double totalCreditos, int forevaId, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpTemas = sgpTemas;
        this.sgpEdiciones = sgpEdiciones;
        this.sgpAsignaturas = sgpAsignaturas;
        this.sgpSecciones = sgpSecciones;
        this.perlecId = perlecId;
        this.totalCreditos = totalCreditos;
        this.forevaId = forevaId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpOfertaAsignatura(SgpOfertaAsignaturaId id, Integer sgpTemas, SgpEdiciones sgpEdiciones, SgpAsignaturas sgpAsignaturas, SgpSecciones sgpSecciones, int perlecId, String nombreGrupo, Short cupoMin, Short cupoMax, Short cupoExterno, Integer horasPresenciales, Integer horasEstudiante, Double totalCreditos, int forevaId, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Date fechaInicia, Date fechaTermina, Date fechaIniciaCalificaciones, Date fechaTerminaCalificaciones) {
       this.id = id;
       this.sgpTemas = sgpTemas;
       this.sgpEdiciones = sgpEdiciones;
       this.sgpAsignaturas = sgpAsignaturas;
       this.sgpSecciones = sgpSecciones;
       this.perlecId = perlecId;
       this.nombreGrupo = nombreGrupo;
       this.cupoMin = cupoMin;
       this.cupoMax = cupoMax;
       this.cupoExterno = cupoExterno;
       this.horasPresenciales = horasPresenciales;
       this.horasEstudiante = horasEstudiante;
       this.totalCreditos = totalCreditos;
       this.forevaId = forevaId;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.fechaInicia = fechaInicia;
       this.fechaTermina = fechaTermina;
       this.fechaIniciaCalificaciones = fechaIniciaCalificaciones;
       this.fechaTerminaCalificaciones = fechaTerminaCalificaciones;
    }
   
    public SgpOfertaAsignaturaId getId() {
        return this.id;
    }
    
    public void setId(SgpOfertaAsignaturaId id) {
        this.id = id;
    }

    public Integer getSgpTemas() {
        return sgpTemas;
    }
    
    public void setSgpTemas(Integer sgpTemas) {
        this.sgpTemas = sgpTemas;
    }
    
    public SgpEdiciones getSgpEdiciones() {
        return this.sgpEdiciones;
    }
    
    public void setSgpEdiciones(SgpEdiciones sgpEdiciones) {
        this.sgpEdiciones = sgpEdiciones;
    }
    public SgpAsignaturas getSgpAsignaturas() {
        return this.sgpAsignaturas;
    }
    
    public void setSgpAsignaturas(SgpAsignaturas sgpAsignaturas) {
        this.sgpAsignaturas = sgpAsignaturas;
    }
    public SgpSecciones getSgpSecciones() {
        return this.sgpSecciones;
    }
    
    public void setSgpSecciones(SgpSecciones sgpSecciones) {
        this.sgpSecciones = sgpSecciones;
    }

    public int getPerlecId() {
        return perlecId;
    }
    
    public void setPerlecId(int perlecId) {
        this.perlecId = perlecId;
    }
    
    public String getNombreGrupo() {
        return this.nombreGrupo;
    }
    
    public void setNombreGrupo(String nombreGrupo) {
        this.nombreGrupo = nombreGrupo;
    }

    public int getCupoExterno() {
        return cupoExterno;
    }
    
    public void setCupoExterno(int cupoExterno) {
        this.cupoExterno = cupoExterno;
    }

    public int getCupoMax() {
        return cupoMax;
    }
    
    public void setCupoMax(int cupoMax) {
        this.cupoMax = cupoMax;
    }

    public int getCupoMin() {
        return cupoMin;
    }
    
    public void setCupoMin(int cupoMin) {
        this.cupoMin = cupoMin;
    }
    
    public Integer getHorasPresenciales() {
        return this.horasPresenciales;
    }
    
    public void setHorasPresenciales(Integer horasPresenciales) {
        this.horasPresenciales = horasPresenciales;
    }
    public Integer getHorasEstudiante() {
        return this.horasEstudiante;
    }
    
    public void setHorasEstudiante(Integer horasEstudiante) {
        this.horasEstudiante = horasEstudiante;
    }

    public Double getTotalCreditos() {
        return totalCreditos;
    }
    
    public void setTotalCreditos(Double totalCreditos) {
        this.totalCreditos = totalCreditos;
    }
    
    public int getForevaId() {
        return this.forevaId;
    }
    
    public void setForevaId(int forevaId) {
        this.forevaId = forevaId;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Date getFechaInicia() {
        return this.fechaInicia;
    }
    
    public void setFechaInicia(Date fechaInicia) {
        this.fechaInicia = fechaInicia;
    }
    public Date getFechaTermina() {
        return this.fechaTermina;
    }
    
    public void setFechaTermina(Date fechaTermina) {
        this.fechaTermina = fechaTermina;
    }
    public Set getSgpOfertaDocenteses() {
        return this.sgpOfertaDocenteses;
    }
    
    public void setSgpOfertaDocenteses(Set sgpOfertaDocenteses) {
        this.sgpOfertaDocenteses = sgpOfertaDocenteses;
    }
    public Set getSgpHorariosOfertases() {
        return this.sgpHorariosOfertases;
    }

    public void setSgpHorariosOfertases(Set sgpHorariosOfertases) {
        this.sgpHorariosOfertases = sgpHorariosOfertases;
    }

    public boolean isSelected() {
        return selected;
    }

    public void setSelected(boolean selected) {
        this.selected = selected;
    }

    public String getNombreTema() {
        return nombreTema;
    }

    public void setNombreTema(String nombreTema) {
        this.nombreTema = nombreTema;
    }
    
    public Date getFechaIniciaCalificaciones() {
        return this.fechaIniciaCalificaciones;
    }
    
    public void setFechaIniciaCalificaciones(Date fechaIniciaCalificaciones) {
        this.fechaIniciaCalificaciones = fechaIniciaCalificaciones;
    }
    public Date getFechaTerminaCalificaciones() {
        return this.fechaTerminaCalificaciones;
    }
    
    public void setFechaTerminaCalificaciones(Date fechaTerminaCalificaciones) {
        this.fechaTerminaCalificaciones = fechaTerminaCalificaciones;
    }

}


