package datos.pojos.sgap;
// Generated 14-mar-2014 11:33:11 by Hibernate Tools 3.2.1.GA



/**
 * SgpOfertaAsignaturaId generated by hbm2java
 */
public class SgpOfertaAsignaturaId  implements java.io.Serializable {


     private int curposId;
     private int edicionId;
     private int asignaturaId;
     private int grupo;

    public SgpOfertaAsignaturaId() {
    }

    public SgpOfertaAsignaturaId(int curposId, int edicionId, int asignaturaId, int grupo) {
       this.curposId = curposId;
       this.edicionId = edicionId;
       this.asignaturaId = asignaturaId;
       this.grupo = grupo;
    }
   
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }
    public int getAsignaturaId() {
        return this.asignaturaId;
    }
    
    public void setAsignaturaId(int asignaturaId) {
        this.asignaturaId = asignaturaId;
    }
    public int getGrupo() {
        return this.grupo;
    }
    
    public void setGrupo(int grupo) {
        this.grupo = grupo;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpOfertaAsignaturaId) ) return false;
		 SgpOfertaAsignaturaId castOther = ( SgpOfertaAsignaturaId ) other; 
         
		 return (this.getCurposId()==castOther.getCurposId())
 && (this.getEdicionId()==castOther.getEdicionId())
 && (this.getAsignaturaId()==castOther.getAsignaturaId())
 && (this.getGrupo()==castOther.getGrupo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getEdicionId();
         result = 37 * result + this.getAsignaturaId();
         result = 37 * result + this.getGrupo();
         return result;
   }   


}


