package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpPresupuestoValoresId generated by hbm2java
 */
public class SgpPresupuestoValoresId  implements java.io.Serializable {


     private int prerubId;
     private int precabId;
     private int curposId;
     private int edicionId;

    public SgpPresupuestoValoresId() {
    }

    public SgpPresupuestoValoresId(int prerubId, int precabId, int curposId, int edicionId) {
       this.prerubId = prerubId;
       this.precabId = precabId;
       this.curposId = curposId;
       this.edicionId = edicionId;
    }
   
    public int getPrerubId() {
        return this.prerubId;
    }
    
    public void setPrerubId(int prerubId) {
        this.prerubId = prerubId;
    }
    public int getPrecabId() {
        return this.precabId;
    }
    
    public void setPrecabId(int precabId) {
        this.precabId = precabId;
    }
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpPresupuestoValoresId) ) return false;
		 SgpPresupuestoValoresId castOther = ( SgpPresupuestoValoresId ) other; 
         
		 return (this.getPrerubId()==castOther.getPrerubId())
 && (this.getPrecabId()==castOther.getPrecabId())
 && (this.getCurposId()==castOther.getCurposId())
 && (this.getEdicionId()==castOther.getEdicionId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPrerubId();
         result = 37 * result + this.getPrecabId();
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getEdicionId();
         return result;
   }   


}


