package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpPlanesModalidadesId generated by hbm2java
 */
public class SgpPlanesModalidadesId  implements java.io.Serializable {


     private int curposId;
     private int placurId;
     private int modalidadId;

    public SgpPlanesModalidadesId() {
    }

    public SgpPlanesModalidadesId(int curposId, int placurId, int modalidadId) {
       this.curposId = curposId;
       this.placurId = placurId;
       this.modalidadId = modalidadId;
    }
   
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getPlacurId() {
        return this.placurId;
    }
    
    public void setPlacurId(int placurId) {
        this.placurId = placurId;
    }
    public int getModalidadId() {
        return this.modalidadId;
    }
    
    public void setModalidadId(int modalidadId) {
        this.modalidadId = modalidadId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpPlanesModalidadesId) ) return false;
		 SgpPlanesModalidadesId castOther = ( SgpPlanesModalidadesId ) other; 
         
		 return (this.getCurposId()==castOther.getCurposId())
 && (this.getPlacurId()==castOther.getPlacurId())
 && (this.getModalidadId()==castOther.getModalidadId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getPlacurId();
         result = 37 * result + this.getModalidadId();
         return result;
   }   


}


