package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.faces.model.SelectItem;

/**
 * SgpPresupuestoValores generated by hbm2java
 */
public class SgpPresupuestoValores implements java.io.Serializable {

    private SgpPresupuestoValoresId id;
    private SgpPresupuestoUnidades sgpPresupuestoUnidades;
    private SgpPresupuestoRubros sgpPresupuestoRubros;
    private SgpEdiciones sgpEdiciones;
    private int cantidad;
    private double costoUnitario;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    //***campos q no son de la base
    private boolean esPadre;
    private SelectItem[] unidadesItems;
    private int unidadSelecteccionadaId;
    /*
     * para validaciones
     */
    private String costoUnitarioString = "0.0";
    private String cantidadString = "0";

    public SgpPresupuestoValores() {
    }

    public SgpPresupuestoValores(SgpPresupuestoValoresId id, SgpPresupuestoRubros sgpPresupuestoRubros, SgpEdiciones sgpEdiciones, int cantidad, double costoUnitario, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
        this.sgpEdiciones = sgpEdiciones;
        this.cantidad = cantidad;
        this.costoUnitario = costoUnitario;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpPresupuestoValores(SgpPresupuestoValoresId id, SgpPresupuestoUnidades sgpPresupuestoUnidades, SgpPresupuestoRubros sgpPresupuestoRubros, SgpEdiciones sgpEdiciones, int cantidad, double costoUnitario, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
        this.id = id;
        this.sgpPresupuestoUnidades = sgpPresupuestoUnidades;
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
        this.sgpEdiciones = sgpEdiciones;
        this.cantidad = cantidad;
        this.costoUnitario = costoUnitario;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
    }

    public SgpPresupuestoValores(SgpPresupuestoValoresId sgpPresupuestoRubrosId, SgpEdiciones sgpEdiciones, SgpPresupuestoRubros sgpPresupuestoRubros, SgpPresupuestoUnidades sgpPresupuestoUnidades, int cantidad, double costoUnitario/*
             * String cantidad, String costoUnitario
             */, char estaactivo, SelectItem[] unidadItems, boolean esPadre, int unidadSelectedId) {
        this.id = sgpPresupuestoRubrosId;
        this.sgpEdiciones = sgpEdiciones;
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
        this.sgpPresupuestoUnidades = sgpPresupuestoUnidades;
        this.cantidad = cantidad;
        this.costoUnitario = costoUnitario;
        this.estaactivo = estaactivo;
        this.unidadesItems = unidadItems;
        this.esPadre = esPadre;
        //modificado
        this.unidadSelecteccionadaId = unidadSelectedId;
        //modificado
        //   this.sgpPresupuestoRubros.setEstitulo(estitulo);

    }

    public SgpPresupuestoValoresId getId() {
        return this.id;
    }

    public void setId(SgpPresupuestoValoresId id) {
        this.id = id;
    }

    public SgpPresupuestoUnidades getSgpPresupuestoUnidades() {
        return this.sgpPresupuestoUnidades;
    }

    public void setSgpPresupuestoUnidades(SgpPresupuestoUnidades sgpPresupuestoUnidades) {
        this.sgpPresupuestoUnidades = sgpPresupuestoUnidades;
    }

    public SgpPresupuestoRubros getSgpPresupuestoRubros() {
        return this.sgpPresupuestoRubros;
    }

    public void setSgpPresupuestoRubros(SgpPresupuestoRubros sgpPresupuestoRubros) {
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
    }

    public SgpEdiciones getSgpEdiciones() {
        return this.sgpEdiciones;
    }

    public void setSgpEdiciones(SgpEdiciones sgpEdiciones) {
        this.sgpEdiciones = sgpEdiciones;
    }

    public int getCantidad() {
        return this.cantidad;
    }

    public void setCantidad(int cantidad) {
        this.cantidad = cantidad;
    }

    public String getCantidadString() {
        return cantidadString;
    }

    public void setCantidadString(String cantidadString) {
        this.cantidadString = cantidadString;
    }

    public double getCostoUnitario() {
        return costoUnitario;
    }

    public void setCostoUnitario(double costoUnitario) {
        this.costoUnitario = costoUnitario;
    }

    public String getCostoUnitarioString() {
        return costoUnitarioString;
    }

    public void setCostoUnitarioString(String costoUnitarioString) {
        this.costoUnitarioString = costoUnitarioString;
    }

    public boolean isEsPadre() {
        return esPadre;
    }

    public void setEsPadre(boolean esPadre) {
        this.esPadre = esPadre;
    }

    public int getUnidadSelecteccionadaId() {
        return unidadSelecteccionadaId;
    }

    public void setUnidadSelecteccionadaId(int unidadSelecteccionadaId) {
        this.unidadSelecteccionadaId = unidadSelecteccionadaId;
    }

    public SelectItem[] getUnidadesItems() {
        return unidadesItems;
    }

    public void setUnidadesItems(SelectItem[] unidadesItems) {
        this.unidadesItems = unidadesItems;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public double getTotal() {
        double total = 0d;
        try {
            //total = Integer.valueOf(cantidad) * Double.valueOf(costoUnitario);
            //total = cantidad * costoUnitario;
            total = Integer.valueOf(cantidadString) * Double.valueOf(costoUnitarioString);
        } catch (Exception e) {
            total = 0d;
        }
        return total;
    }
}
