package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpPresupuestoRubrosId generated by hbm2java
 */
public class SgpPresupuestoRubrosId  implements java.io.Serializable {


     private int id;
     private int precabId;

    public SgpPresupuestoRubrosId() {
    }

    public SgpPresupuestoRubrosId(int id, int precabId) {
       this.id = id;
       this.precabId = precabId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getPrecabId() {
        return this.precabId;
    }
    
    public void setPrecabId(int precabId) {
        this.precabId = precabId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpPresupuestoRubrosId) ) return false;
		 SgpPresupuestoRubrosId castOther = ( SgpPresupuestoRubrosId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getPrecabId()==castOther.getPrecabId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getPrecabId();
         return result;
   }   


}


