package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpPlanesCurso generated by hbm2java
 */
public class SgpPlanesCurso implements java.io.Serializable {

    private SgpPlanesCursoId id;
    private SgpResolucionesSenescyt sgpResolucionesSenescyt;
    private SgpComponentesCabeceras sgpComponentesCabeceras;
    private SgpCursosPostgrado sgpCursosPostgrado;
    private String nombre;
    private BigDecimal creditosGrado;
    private BigDecimal creditosTesis;
    private int inseduId;
    private int ubicacionId;
    private String tipoSede;
    private char envigencia;
    private int dependenciaId;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String actualizado;
    private Date fechaActualizacion;
    private String direccion;
    private Integer numeroSemestres;
    private Set sgpActividadesCronogramas = new HashSet(0);
    private Set sgpComponentesPlaneses = new HashSet(0);
    private Set sgpMallases = new HashSet(0);
    private Set sgpPlanesModalidadeses = new HashSet(0);
    private Set sgpInstitucionesCursos = new HashSet(0);
    private Set sgpLineasInvestigacions = new HashSet(0);
    private Set sgpEjesTematicoses = new HashSet(0);
    private Integer nroInstanciasMatricula;

    public SgpPlanesCurso() {
    }

    public SgpPlanesCurso(SgpPlanesCursoId id, SgpResolucionesSenescyt sgpResolucionesSenescyt, SgpComponentesCabeceras sgpComponentesCabeceras, SgpCursosPostgrado sgpCursosPostgrado, String nombre, BigDecimal creditosGrado, BigDecimal creditosTesis, int inseduId, int ubicacionId, String tipoSede, char envigencia, int dependenciaId, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpResolucionesSenescyt = sgpResolucionesSenescyt;
        this.sgpComponentesCabeceras = sgpComponentesCabeceras;
        this.sgpCursosPostgrado = sgpCursosPostgrado;
        this.nombre = nombre;
        this.creditosGrado = creditosGrado;
        this.creditosTesis = creditosTesis;
        this.inseduId = inseduId;
        this.ubicacionId = ubicacionId;
        this.tipoSede = tipoSede;
        this.envigencia = envigencia;
        this.dependenciaId = dependenciaId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpPlanesCurso(SgpPlanesCursoId id, SgpResolucionesSenescyt sgpResolucionesSenescyt, SgpComponentesCabeceras sgpComponentesCabeceras, SgpCursosPostgrado sgpCursosPostgrado, String nombre, BigDecimal creditosGrado, BigDecimal creditosTesis, int inseduId, int ubicacionId, String tipoSede, char envigencia, int dependenciaId, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, String direccion) {
        this.id = id;
        this.sgpResolucionesSenescyt = sgpResolucionesSenescyt;
        this.sgpComponentesCabeceras = sgpComponentesCabeceras;
        this.sgpCursosPostgrado = sgpCursosPostgrado;
        this.nombre = nombre;
        this.creditosGrado = creditosGrado;
        this.creditosTesis = creditosTesis;
        this.inseduId = inseduId;
        this.ubicacionId = ubicacionId;
        this.tipoSede = tipoSede;
        this.envigencia = envigencia;
        this.dependenciaId = dependenciaId;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.actualizado = actualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.direccion = direccion;
    }

   
    public SgpPlanesCursoId getId() {
        return this.id;
    }

    public void setId(SgpPlanesCursoId id) {
        this.id = id;
    }

    public SgpResolucionesSenescyt getSgpResolucionesSenescyt() {
        return this.sgpResolucionesSenescyt;
    }

    public void setSgpResolucionesSenescyt(SgpResolucionesSenescyt sgpResolucionesSenescyt) {
        this.sgpResolucionesSenescyt = sgpResolucionesSenescyt;
    }

    public SgpComponentesCabeceras getSgpComponentesCabeceras() {
        return this.sgpComponentesCabeceras;
    }

    public void setSgpComponentesCabeceras(SgpComponentesCabeceras sgpComponentesCabeceras) {
        this.sgpComponentesCabeceras = sgpComponentesCabeceras;
    }

    public SgpCursosPostgrado getSgpCursosPostgrado() {
        return this.sgpCursosPostgrado;
    }

    public void setSgpCursosPostgrado(SgpCursosPostgrado sgpCursosPostgrado) {
        this.sgpCursosPostgrado = sgpCursosPostgrado;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public BigDecimal getCreditosGrado() {
        return creditosGrado;
    }

    public void setCreditosGrado(BigDecimal creditosGrado) {
        this.creditosGrado = creditosGrado;
    }

    public BigDecimal getCreditosTesis() {
        return creditosTesis;
    }

    public void setCreditosTesis(BigDecimal creditosTesis) {
        this.creditosTesis = creditosTesis;
    }

    public int getInseduId() {
        return this.inseduId;
    }

    public void setInseduId(int inseduId) {
        this.inseduId = inseduId;
    }

    public int getUbicacionId() {
        return this.ubicacionId;
    }

    public void setUbicacionId(int ubicacionId) {
        this.ubicacionId = ubicacionId;
    }

    public String getTipoSede() {
        return this.tipoSede;
    }

    public void setTipoSede(String tipoSede) {
        this.tipoSede = tipoSede;
    }

    public char getEnvigencia() {
        return envigencia;
    }

    public void setEnvigencia(char envigencia) {
        this.envigencia = envigencia;
    }


    public int getDependenciaId() {
        return this.dependenciaId;
    }

    public void setDependenciaId(int dependenciaId) {
        this.dependenciaId = dependenciaId;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getActualizado() {
        return this.actualizado;
    }

    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public String getDireccion() {
        return direccion;
    }

    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }

    
    public Set getSgpActividadesCronogramas() {
        return this.sgpActividadesCronogramas;
    }

    public void setSgpActividadesCronogramas(Set sgpActividadesCronogramas) {
        this.sgpActividadesCronogramas = sgpActividadesCronogramas;
    }

    public Set getSgpComponentesPlaneses() {
        return this.sgpComponentesPlaneses;
    }

    public void setSgpComponentesPlaneses(Set sgpComponentesPlaneses) {
        this.sgpComponentesPlaneses = sgpComponentesPlaneses;
    }

    public Set getSgpMallases() {
        return this.sgpMallases;
    }

    public void setSgpMallases(Set sgpMallases) {
        this.sgpMallases = sgpMallases;
    }

    public Set getSgpPlanesModalidadeses() {
        return this.sgpPlanesModalidadeses;
    }

    public void setSgpPlanesModalidadeses(Set sgpPlanesModalidadeses) {
        this.sgpPlanesModalidadeses = sgpPlanesModalidadeses;
    }

    public Set getSgpInstitucionesCursos() {
        return this.sgpInstitucionesCursos;
    }

    public void setSgpInstitucionesCursos(Set sgpInstitucionesCursos) {
        this.sgpInstitucionesCursos = sgpInstitucionesCursos;
    }

    public Set getSgpLineasInvestigacions() {
        return this.sgpLineasInvestigacions;
    }

    public void setSgpLineasInvestigacions(Set sgpLineasInvestigacions) {
        this.sgpLineasInvestigacions = sgpLineasInvestigacions;
    }

    public Set getSgpEjesTematicoses() {
        return this.sgpEjesTematicoses;
    }

    public void setSgpEjesTematicoses(Set sgpEjesTematicoses) {
        this.sgpEjesTematicoses = sgpEjesTematicoses;
    }

    public Integer getNumeroSemestres() {
        return numeroSemestres;
    }

    public void setNumeroSemestres(Integer numeroSemestres) {
        this.numeroSemestres = numeroSemestres;
    }

    public Integer getNroInstanciasMatricula() {
        return this.nroInstanciasMatricula;
    }
    
    public void setNroInstanciasMatricula(Integer nroInstanciasMatricula) {
        this.nroInstanciasMatricula = nroInstanciasMatricula;
    }
    
}
