package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpPresupuestoRubros generated by hbm2java
 */
public class SgpPresupuestoRubros implements java.io.Serializable {

    private SgpPresupuestoRubrosId id;
    private SgpPresupuestoCabeceras sgpPresupuestoCabeceras;
    private SgpPresupuestoRubros sgpPresupuestoRubros;
    private String numero;
    private String nombre;
    private char estitulo;
    private String tipoRubro;
    private short orden;
    private char estaactivo;
    private String creado;
    private Date fechaCreacion;
    private String atualizado;
    private Date fechaActualizacion;
    private Set sgpPresupuestoRubroses = new HashSet(0);
    private Set sgpPresupuestoValoreses = new HashSet(0);
    private String sangria = "";

    public SgpPresupuestoRubros() {
    }

    public SgpPresupuestoRubros(SgpPresupuestoRubrosId id, SgpPresupuestoCabeceras sgpPresupuestoCabeceras, SgpPresupuestoRubros sgpPresupuestoRubros, String nombre, char estitulo, String tipoRubro, short orden, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpPresupuestoCabeceras = sgpPresupuestoCabeceras;
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
        this.nombre = nombre;
        this.estitulo = estitulo;
        this.tipoRubro = tipoRubro;
        this.orden = orden;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }

    public SgpPresupuestoRubros(SgpPresupuestoRubrosId id, SgpPresupuestoCabeceras sgpPresupuestoCabeceras, SgpPresupuestoRubros sgpPresupuestoRubros, String numero, String nombre, char estitulo, String tipoRubro, short orden, char estaactivo, String creado, Date fechaCreacion, String atualizado, Date fechaActualizacion, Set sgpPresupuestoRubroses, Set sgpPresupuestoValoreses) {
        this.id = id;
        this.sgpPresupuestoCabeceras = sgpPresupuestoCabeceras;
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
        this.numero = numero;
        this.nombre = nombre;
        this.estitulo = estitulo;
        this.tipoRubro = tipoRubro;
        this.orden = orden;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
        this.atualizado = atualizado;
        this.fechaActualizacion = fechaActualizacion;
        this.sgpPresupuestoRubroses = sgpPresupuestoRubroses;
        this.sgpPresupuestoValoreses = sgpPresupuestoValoreses;
    }

    public SgpPresupuestoRubrosId getId() {
        return this.id;
    }

    public void setId(SgpPresupuestoRubrosId id) {
        this.id = id;
    }

    public SgpPresupuestoCabeceras getSgpPresupuestoCabeceras() {
        return this.sgpPresupuestoCabeceras;
    }

    public void setSgpPresupuestoCabeceras(SgpPresupuestoCabeceras sgpPresupuestoCabeceras) {
        this.sgpPresupuestoCabeceras = sgpPresupuestoCabeceras;
    }

    public SgpPresupuestoRubros getSgpPresupuestoRubros() {
        return this.sgpPresupuestoRubros;
    }

    public void setSgpPresupuestoRubros(SgpPresupuestoRubros sgpPresupuestoRubros) {
        this.sgpPresupuestoRubros = sgpPresupuestoRubros;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getNombre() {
        return this.nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public char getEstitulo() {
        return this.estitulo;
    }

    public void setEstitulo(char estitulo) {
        this.estitulo = estitulo;
    }

    public String getTipoRubro() {
        return this.tipoRubro;
    }

    public void setTipoRubro(String tipoRubro) {
        this.tipoRubro = tipoRubro;
    }

    public short getOrden() {
        return this.orden;
    }

    public void setOrden(short orden) {
        this.orden = orden;
    }

    public char getEstaactivo() {
        return this.estaactivo;
    }

    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }

    public String getCreado() {
        return this.creado;
    }

    public void setCreado(String creado) {
        this.creado = creado;
    }

    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }

    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }

    public String getAtualizado() {
        return this.atualizado;
    }

    public void setAtualizado(String atualizado) {
        this.atualizado = atualizado;
    }

    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }

    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }

    public Set getSgpPresupuestoRubroses() {
        return this.sgpPresupuestoRubroses;
    }

    public void setSgpPresupuestoRubroses(Set sgpPresupuestoRubroses) {
        this.sgpPresupuestoRubroses = sgpPresupuestoRubroses;
    }

    public Set getSgpPresupuestoValoreses() {
        return this.sgpPresupuestoValoreses;
    }

    public void setSgpPresupuestoValoreses(Set sgpPresupuestoValoreses) {
        this.sgpPresupuestoValoreses = sgpPresupuestoValoreses;
    }

    public String getSangria() {
        return sangria;
    }

    public void setSangria(String sangria) {
        this.sangria = sangria;
    }
}
