package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpRegistrosAportes generated by hbm2java
 */
public class SgpRegistrosAportes  implements java.io.Serializable {


     private SgpRegistrosAportesId id;
     private SgpEvaluacionesAportes sgpEvaluacionesAportes;
     private SgpRegistrosCabeceras sgpRegistrosCabeceras;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpRegistrosAportes() {
    }

	
    public SgpRegistrosAportes(SgpRegistrosAportesId id, SgpEvaluacionesAportes sgpEvaluacionesAportes, SgpRegistrosCabeceras sgpRegistrosCabeceras, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpEvaluacionesAportes = sgpEvaluacionesAportes;
        this.sgpRegistrosCabeceras = sgpRegistrosCabeceras;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpRegistrosAportes(SgpRegistrosAportesId id, SgpEvaluacionesAportes sgpEvaluacionesAportes, SgpRegistrosCabeceras sgpRegistrosCabeceras, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpEvaluacionesAportes = sgpEvaluacionesAportes;
       this.sgpRegistrosCabeceras = sgpRegistrosCabeceras;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public SgpRegistrosAportesId getId() {
        return this.id;
    }
    
    public void setId(SgpRegistrosAportesId id) {
        this.id = id;
    }
    public SgpEvaluacionesAportes getSgpEvaluacionesAportes() {
        return this.sgpEvaluacionesAportes;
    }
    
    public void setSgpEvaluacionesAportes(SgpEvaluacionesAportes sgpEvaluacionesAportes) {
        this.sgpEvaluacionesAportes = sgpEvaluacionesAportes;
    }
    public SgpRegistrosCabeceras getSgpRegistrosCabeceras() {
        return this.sgpRegistrosCabeceras;
    }
    
    public void setSgpRegistrosCabeceras(SgpRegistrosCabeceras sgpRegistrosCabeceras) {
        this.sgpRegistrosCabeceras = sgpRegistrosCabeceras;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


