package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpRegistrosCabecerasId generated by hbm2java
 */
public class SgpRegistrosCabecerasId  implements java.io.Serializable {


     private int id;
     private int forevaId;

    public SgpRegistrosCabecerasId() {
    }

    public SgpRegistrosCabecerasId(int id, int forevaId) {
       this.id = id;
       this.forevaId = forevaId;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public int getForevaId() {
        return this.forevaId;
    }
    
    public void setForevaId(int forevaId) {
        this.forevaId = forevaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpRegistrosCabecerasId) ) return false;
		 SgpRegistrosCabecerasId castOther = ( SgpRegistrosCabecerasId ) other; 
         
		 return (this.getId()==castOther.getId())
 && (this.getForevaId()==castOther.getForevaId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getId();
         result = 37 * result + this.getForevaId();
         return result;
   }   


}


