package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.sql.Clob;
import java.util.Date;

/**
 * SgpSilaboComponentes generated by hbm2java
 */
public class SgpSilaboComponentes  implements java.io.Serializable {


     private SgpSilaboComponentesId id;
     private SgpSilabos sgpSilabos;
     private SgpSilaboDetalles sgpSilaboDetalles;
     private String valor;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpSilaboComponentes() {
    }

	
    public SgpSilaboComponentes(SgpSilaboComponentesId id, SgpSilabos sgpSilabos, SgpSilaboDetalles sgpSilaboDetalles, String valor, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpSilabos = sgpSilabos;
        this.sgpSilaboDetalles = sgpSilaboDetalles;
        this.valor = valor;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpSilaboComponentes(SgpSilaboComponentesId id, SgpSilabos sgpSilabos, SgpSilaboDetalles sgpSilaboDetalles, String valor, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpSilabos = sgpSilabos;
       this.sgpSilaboDetalles = sgpSilaboDetalles;
       this.valor = valor;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public SgpSilaboComponentesId getId() {
        return this.id;
    }
    
    public void setId(SgpSilaboComponentesId id) {
        this.id = id;
    }
    public SgpSilabos getSgpSilabos() {
        return this.sgpSilabos;
    }
    
    public void setSgpSilabos(SgpSilabos sgpSilabos) {
        this.sgpSilabos = sgpSilabos;
    }
    public SgpSilaboDetalles getSgpSilaboDetalles() {
        return this.sgpSilaboDetalles;
    }
    
    public void setSgpSilaboDetalles(SgpSilaboDetalles sgpSilaboDetalles) {
        this.sgpSilaboDetalles = sgpSilaboDetalles;
    }

    public String getValor() {
        return valor;
    }

    public void setValor(String valor) {
        this.valor = valor;
    }
  
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


