package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpSilabos generated by hbm2java
 */
public class SgpSilabos  implements java.io.Serializable {


     private SgpSilabosId id;
     private SgpDocumentosBinarios sgpDocumentosBinarios;
     private SgpEdiciones sgpEdiciones;
     private SgpAsignaturasMallas sgpAsignaturasMallas;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set sgpSilaboComponenteses = new HashSet(0);

    public SgpSilabos() {
    }

	
    public SgpSilabos(SgpSilabosId id, SgpEdiciones sgpEdiciones, SgpAsignaturasMallas sgpAsignaturasMallas, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpEdiciones = sgpEdiciones;
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpSilabos(SgpSilabosId id, SgpDocumentosBinarios sgpDocumentosBinarios, SgpEdiciones sgpEdiciones, SgpAsignaturasMallas sgpAsignaturasMallas, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpSilaboComponenteses) {
       this.id = id;
       this.sgpDocumentosBinarios = sgpDocumentosBinarios;
       this.sgpEdiciones = sgpEdiciones;
       this.sgpAsignaturasMallas = sgpAsignaturasMallas;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpSilaboComponenteses = sgpSilaboComponenteses;
    }
   
    public SgpSilabosId getId() {
        return this.id;
    }
    
    public void setId(SgpSilabosId id) {
        this.id = id;
    }
    public SgpDocumentosBinarios getSgpDocumentosBinarios() {
        return this.sgpDocumentosBinarios;
    }
    
    public void setSgpDocumentosBinarios(SgpDocumentosBinarios sgpDocumentosBinarios) {
        this.sgpDocumentosBinarios = sgpDocumentosBinarios;
    }
    public SgpEdiciones getSgpEdiciones() {
        return this.sgpEdiciones;
    }
    
    public void setSgpEdiciones(SgpEdiciones sgpEdiciones) {
        this.sgpEdiciones = sgpEdiciones;
    }
    public SgpAsignaturasMallas getSgpAsignaturasMallas() {
        return this.sgpAsignaturasMallas;
    }
    
    public void setSgpAsignaturasMallas(SgpAsignaturasMallas sgpAsignaturasMallas) {
        this.sgpAsignaturasMallas = sgpAsignaturasMallas;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getSgpSilaboComponenteses() {
        return this.sgpSilaboComponenteses;
    }
    
    public void setSgpSilaboComponenteses(Set sgpSilaboComponenteses) {
        this.sgpSilaboComponenteses = sgpSilaboComponenteses;
    }




}


