package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpSilabosId generated by hbm2java
 */
public class SgpSilabosId  implements java.io.Serializable {


     private int asignaturaId;
     private int edicionId;
     private int curposId;

    public SgpSilabosId() {
    }

    public SgpSilabosId(int asignaturaId, int edicionId, int curposId) {
       this.asignaturaId = asignaturaId;
       this.edicionId = edicionId;
       this.curposId = curposId;
    }
   
    public int getAsignaturaId() {
        return this.asignaturaId;
    }
    
    public void setAsignaturaId(int asignaturaId) {
        this.asignaturaId = asignaturaId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpSilabosId) ) return false;
		 SgpSilabosId castOther = ( SgpSilabosId ) other; 
         
		 return (this.getAsignaturaId()==castOther.getAsignaturaId())
 && (this.getEdicionId()==castOther.getEdicionId())
 && (this.getCurposId()==castOther.getCurposId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAsignaturaId();
         result = 37 * result + this.getEdicionId();
         result = 37 * result + this.getCurposId();
         return result;
   }   


}


