package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpSilaboDetallesId generated by hbm2java
 */
public class SgpSilaboDetallesId  implements java.io.Serializable {


     private int silcabId;
     private int componenteId;

    public SgpSilaboDetallesId() {
    }

    public SgpSilaboDetallesId(int silcabId, int componenteId) {
       this.silcabId = silcabId;
       this.componenteId = componenteId;
    }
   
    public int getSilcabId() {
        return this.silcabId;
    }
    
    public void setSilcabId(int silcabId) {
        this.silcabId = silcabId;
    }
    public int getComponenteId() {
        return this.componenteId;
    }
    
    public void setComponenteId(int componenteId) {
        this.componenteId = componenteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpSilaboDetallesId) ) return false;
		 SgpSilaboDetallesId castOther = ( SgpSilaboDetallesId ) other; 
         
		 return (this.getSilcabId()==castOther.getSilcabId())
 && (this.getComponenteId()==castOther.getComponenteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSilcabId();
         result = 37 * result + this.getComponenteId();
         return result;
   }   


}


