package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpSilaboComponentesId generated by hbm2java
 */
public class SgpSilaboComponentesId  implements java.io.Serializable {


     private int asignaturaId;
     private int edicionId;
     private int curposId;
     private int silcabId;
     private int componenteId;

    public SgpSilaboComponentesId() {
    }

    public SgpSilaboComponentesId(int asignaturaId, int edicionId, int curposId, int silcabId, int componenteId) {
       this.asignaturaId = asignaturaId;
       this.edicionId = edicionId;
       this.curposId = curposId;
       this.silcabId = silcabId;
       this.componenteId = componenteId;
    }
   
    public int getAsignaturaId() {
        return this.asignaturaId;
    }
    
    public void setAsignaturaId(int asignaturaId) {
        this.asignaturaId = asignaturaId;
    }
    public int getEdicionId() {
        return this.edicionId;
    }
    
    public void setEdicionId(int edicionId) {
        this.edicionId = edicionId;
    }
    public int getCurposId() {
        return this.curposId;
    }
    
    public void setCurposId(int curposId) {
        this.curposId = curposId;
    }
    public int getSilcabId() {
        return this.silcabId;
    }
    
    public void setSilcabId(int silcabId) {
        this.silcabId = silcabId;
    }
    public int getComponenteId() {
        return this.componenteId;
    }
    
    public void setComponenteId(int componenteId) {
        this.componenteId = componenteId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpSilaboComponentesId) ) return false;
		 SgpSilaboComponentesId castOther = ( SgpSilaboComponentesId ) other; 
         
		 return (this.getAsignaturaId()==castOther.getAsignaturaId())
 && (this.getEdicionId()==castOther.getEdicionId())
 && (this.getCurposId()==castOther.getCurposId())
 && (this.getSilcabId()==castOther.getSilcabId())
 && (this.getComponenteId()==castOther.getComponenteId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAsignaturaId();
         result = 37 * result + this.getEdicionId();
         result = 37 * result + this.getCurposId();
         result = 37 * result + this.getSilcabId();
         result = 37 * result + this.getComponenteId();
         return result;
   }   


}


