package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpSilaboDetalles generated by hbm2java
 */
public class SgpSilaboDetalles  implements java.io.Serializable {


     private SgpSilaboDetallesId id;
     private SgpSilaboCabeceras sgpSilaboCabeceras;
     private SgpComponentes sgpComponentes;
     private String numero;
     private short orden;
     private char publicable;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set sgpSilaboComponenteses = new HashSet(0);

    public SgpSilaboDetalles() {
    }

	
    public SgpSilaboDetalles(SgpSilaboDetallesId id, SgpSilaboCabeceras sgpSilaboCabeceras, SgpComponentes sgpComponentes, String numero, short orden, char publicable, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpSilaboCabeceras = sgpSilaboCabeceras;
        this.sgpComponentes = sgpComponentes;
        this.numero = numero;
        this.orden = orden;
        this.publicable = publicable;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpSilaboDetalles(SgpSilaboDetallesId id, SgpSilaboCabeceras sgpSilaboCabeceras, SgpComponentes sgpComponentes, String numero, short orden, char publicable, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpSilaboComponenteses) {
       this.id = id;
       this.sgpSilaboCabeceras = sgpSilaboCabeceras;
       this.sgpComponentes = sgpComponentes;
       this.numero = numero;
       this.orden = orden;
       this.publicable = publicable;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpSilaboComponenteses = sgpSilaboComponenteses;
    }
   
    public SgpSilaboDetallesId getId() {
        return this.id;
    }
    
    public void setId(SgpSilaboDetallesId id) {
        this.id = id;
    }
    public SgpSilaboCabeceras getSgpSilaboCabeceras() {
        return this.sgpSilaboCabeceras;
    }
    
    public void setSgpSilaboCabeceras(SgpSilaboCabeceras sgpSilaboCabeceras) {
        this.sgpSilaboCabeceras = sgpSilaboCabeceras;
    }
    public SgpComponentes getSgpComponentes() {
        return this.sgpComponentes;
    }
    
    public void setSgpComponentes(SgpComponentes sgpComponentes) {
        this.sgpComponentes = sgpComponentes;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public short getOrden() {
        return this.orden;
    }
    
    public void setOrden(short orden) {
        this.orden = orden;
    }
    public char getPublicable() {
        return this.publicable;
    }
    
    public void setPublicable(char publicable) {
        this.publicable = publicable;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getSgpSilaboComponenteses() {
        return this.sgpSilaboComponenteses;
    }
    
    public void setSgpSilaboComponenteses(Set sgpSilaboComponenteses) {
        this.sgpSilaboComponenteses = sgpSilaboComponenteses;
    }




}


