package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpTrabajoPersonas generated by hbm2java
 */
public class SgpTrabajoPersonas  implements java.io.Serializable {


     private SgpTrabajoPersonasId id;
     private SgpTrabajosTitulacion sgpTrabajosTitulacion;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;

    public SgpTrabajoPersonas() {
    }

	
    public SgpTrabajoPersonas(SgpTrabajoPersonasId id, SgpTrabajosTitulacion sgpTrabajosTitulacion, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.sgpTrabajosTitulacion = sgpTrabajosTitulacion;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpTrabajoPersonas(SgpTrabajoPersonasId id, SgpTrabajosTitulacion sgpTrabajosTitulacion, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion) {
       this.id = id;
       this.sgpTrabajosTitulacion = sgpTrabajosTitulacion;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
    }
   
    public SgpTrabajoPersonasId getId() {
        return this.id;
    }
    
    public void setId(SgpTrabajoPersonasId id) {
        this.id = id;
    }
    public SgpTrabajosTitulacion getSgpTrabajosTitulacion() {
        return this.sgpTrabajosTitulacion;
    }
    
    public void setSgpTrabajosTitulacion(SgpTrabajosTitulacion sgpTrabajosTitulacion) {
        this.sgpTrabajosTitulacion = sgpTrabajosTitulacion;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }




}


