package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpTrabajosTitulacion generated by hbm2java
 */
public class SgpTrabajosTitulacion  implements java.io.Serializable {


     private SgpTrabajosTitulacionId id;
     private String titulo;
     private String descripcion;
     private BigDecimal notaDocumento;
     private BigDecimal notaSustentacion;
     private String estadoAprobacion;
     private Short porcentajeAvance;
     private char disenoAprobado;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fechaActualizacion;
     private Set sgpTrabajoPersonases = new HashSet(0);
     private Set sgpActividadesTitulacions = new HashSet(0);

    public SgpTrabajosTitulacion() {
    }

	
    public SgpTrabajosTitulacion(SgpTrabajosTitulacionId id, String titulo, String descripcion, char disenoAprobado, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.titulo = titulo;
        this.descripcion = descripcion;
        this.disenoAprobado = disenoAprobado;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpTrabajosTitulacion(SgpTrabajosTitulacionId id, String titulo, String descripcion, BigDecimal notaDocumento, BigDecimal notaSustentacion, String estadoAprobacion, Short porcentajeAvance, char disenoAprobado, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fechaActualizacion, Set sgpTrabajoPersonases, Set sgpActividadesTitulacions) {
       this.id = id;
       this.titulo = titulo;
       this.descripcion = descripcion;
       this.notaDocumento = notaDocumento;
       this.notaSustentacion = notaSustentacion;
       this.estadoAprobacion = estadoAprobacion;
       this.porcentajeAvance = porcentajeAvance;
       this.disenoAprobado = disenoAprobado;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fechaActualizacion = fechaActualizacion;
       this.sgpTrabajoPersonases = sgpTrabajoPersonases;
       this.sgpActividadesTitulacions = sgpActividadesTitulacions;
    }
   
    public SgpTrabajosTitulacionId getId() {
        return this.id;
    }
    
    public void setId(SgpTrabajosTitulacionId id) {
        this.id = id;
    }
    public String getTitulo() {
        return this.titulo;
    }
    
    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public BigDecimal getNotaDocumento() {
        return this.notaDocumento;
    }
    
    public void setNotaDocumento(BigDecimal notaDocumento) {
        this.notaDocumento = notaDocumento;
    }
    public BigDecimal getNotaSustentacion() {
        return this.notaSustentacion;
    }
    
    public void setNotaSustentacion(BigDecimal notaSustentacion) {
        this.notaSustentacion = notaSustentacion;
    }
    public String getEstadoAprobacion() {
        return this.estadoAprobacion;
    }
    
    public void setEstadoAprobacion(String estadoAprobacion) {
        this.estadoAprobacion = estadoAprobacion;
    }
    public Short getPorcentajeAvance() {
        return this.porcentajeAvance;
    }
    
    public void setPorcentajeAvance(Short porcentajeAvance) {
        this.porcentajeAvance = porcentajeAvance;
    }
    public char getDisenoAprobado() {
        return this.disenoAprobado;
    }
    
    public void setDisenoAprobado(char disenoAprobado) {
        this.disenoAprobado = disenoAprobado;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFechaActualizacion() {
        return this.fechaActualizacion;
    }
    
    public void setFechaActualizacion(Date fechaActualizacion) {
        this.fechaActualizacion = fechaActualizacion;
    }
    public Set getSgpTrabajoPersonases() {
        return this.sgpTrabajoPersonases;
    }
    
    public void setSgpTrabajoPersonases(Set sgpTrabajoPersonases) {
        this.sgpTrabajoPersonases = sgpTrabajoPersonases;
    }
    public Set getSgpActividadesTitulacions() {
        return this.sgpActividadesTitulacions;
    }
    
    public void setSgpActividadesTitulacions(Set sgpActividadesTitulacions) {
        this.sgpActividadesTitulacions = sgpActividadesTitulacions;
    }




}


