package datos.pojos.sgap;
// Generated 04/04/2014 10:30:05 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpTesisProrroga generated by hbm2java
 */
public class SgpTesisProrroga  implements java.io.Serializable {


     private int tepId;
     private SgpTesis sgpTesis;
     private short tepNumProrroga;
     private Date tepFechaAprobacion;
     private String tepNumDocumento;
     private Short tepTiempo;
     private String tepFormatoTiempo;
     private Date tepFechaInicia;
     private Date tepFechaFin;
     private char tepEstaactivo;
     private String tepCreado;
     private Date tepFechaCreacion;
     private String tepActualizado;
     private Date tepFechaActualizacion;
     private boolean seleccionado = false;

    public SgpTesisProrroga() {
    }

	
    public SgpTesisProrroga(int tepId, SgpTesis sgpTesis, short tepNumProrroga, Date tepFechaAprobacion, String tepNumDocumento, String tepFormatoTiempo, Date tepFechaInicia, Date tepFechaFin, char tepEstaactivo, String tepCreado, Date tepFechaCreacion) {
        this.tepId = tepId;
        this.sgpTesis = sgpTesis;
        this.tepNumProrroga = tepNumProrroga;
        this.tepFechaAprobacion = tepFechaAprobacion;
        this.tepNumDocumento = tepNumDocumento;
        this.tepFormatoTiempo = tepFormatoTiempo;
        this.tepFechaInicia = tepFechaInicia;
        this.tepFechaFin = tepFechaFin;
        this.tepEstaactivo = tepEstaactivo;
        this.tepCreado = tepCreado;
        this.tepFechaCreacion = tepFechaCreacion;
    }
    public SgpTesisProrroga(int tepId, SgpTesis sgpTesis, short tepNumProrroga, Date tepFechaAprobacion, String tepNumDocumento, Short tepTiempo, String tepFormatoTiempo, Date tepFechaInicia, Date tepFechaFin, char tepEstaactivo, String tepCreado, Date tepFechaCreacion, String tepActualizado, Date tepFechaActualizacion) {
       this.tepId = tepId;
       this.sgpTesis = sgpTesis;
       this.tepNumProrroga = tepNumProrroga;
       this.tepFechaAprobacion = tepFechaAprobacion;
       this.tepNumDocumento = tepNumDocumento;
       this.tepTiempo = tepTiempo;
       this.tepFormatoTiempo = tepFormatoTiempo;
       this.tepFechaInicia = tepFechaInicia;
       this.tepFechaFin = tepFechaFin;
       this.tepEstaactivo = tepEstaactivo;
       this.tepCreado = tepCreado;
       this.tepFechaCreacion = tepFechaCreacion;
       this.tepActualizado = tepActualizado;
       this.tepFechaActualizacion = tepFechaActualizacion;
    }
   
    public int getTepId() {
        return this.tepId;
    }
    
    public void setTepId(int tepId) {
        this.tepId = tepId;
    }
    public SgpTesis getSgpTesis() {
        return this.sgpTesis;
    }
    
    public void setSgpTesis(SgpTesis sgpTesis) {
        this.sgpTesis = sgpTesis;
    }
    public short getTepNumProrroga() {
        return this.tepNumProrroga;
    }
    
    public void setTepNumProrroga(short tepNumProrroga) {
        this.tepNumProrroga = tepNumProrroga;
    }
    public Date getTepFechaAprobacion() {
        return this.tepFechaAprobacion;
    }
    
    public void setTepFechaAprobacion(Date tepFechaAprobacion) {
        this.tepFechaAprobacion = tepFechaAprobacion;
    }
    public String getTepNumDocumento() {
        return this.tepNumDocumento;
    }
    
    public void setTepNumDocumento(String tepNumDocumento) {
        this.tepNumDocumento = tepNumDocumento;
    }
    public Short getTepTiempo() {
        return this.tepTiempo;
    }
    
    public void setTepTiempo(Short tepTiempo) {
        this.tepTiempo = tepTiempo;
    }
    public String getTepFormatoTiempo() {
        return this.tepFormatoTiempo;
    }
    
    public void setTepFormatoTiempo(String tepFormatoTiempo) {
        this.tepFormatoTiempo = tepFormatoTiempo;
    }
    public Date getTepFechaInicia() {
        return this.tepFechaInicia;
    }
    
    public void setTepFechaInicia(Date tepFechaInicia) {
        this.tepFechaInicia = tepFechaInicia;
    }
    public Date getTepFechaFin() {
        return this.tepFechaFin;
    }
    
    public void setTepFechaFin(Date tepFechaFin) {
        this.tepFechaFin = tepFechaFin;
    }
    public char getTepEstaactivo() {
        return this.tepEstaactivo;
    }
    
    public void setTepEstaactivo(char tepEstaactivo) {
        this.tepEstaactivo = tepEstaactivo;
    }
    public String getTepCreado() {
        return this.tepCreado;
    }
    
    public void setTepCreado(String tepCreado) {
        this.tepCreado = tepCreado;
    }
    public Date getTepFechaCreacion() {
        return this.tepFechaCreacion;
    }
    
    public void setTepFechaCreacion(Date tepFechaCreacion) {
        this.tepFechaCreacion = tepFechaCreacion;
    }
    public String getTepActualizado() {
        return this.tepActualizado;
    }
    
    public void setTepActualizado(String tepActualizado) {
        this.tepActualizado = tepActualizado;
    }
    public Date getTepFechaActualizacion() {
        return this.tepFechaActualizacion;
    }
    
    public void setTepFechaActualizacion(Date tepFechaActualizacion) {
        this.tepFechaActualizacion = tepFechaActualizacion;
    }

    public boolean isSeleccionado() {
        return seleccionado;
    }

    public void setSeleccionado(boolean seleccionado) {
        this.seleccionado = seleccionado;
    }


}


