package datos.pojos.sgap;
// Generated 04/04/2014 10:30:05 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpTesisAnulacion generated by hbm2java
 */
public class SgpTesisAnulacion  implements java.io.Serializable {


     private int tanId;
     private SgpTesis sgpTesis;
     private Date tanFechaAprobacion;
     private String tanNroDocumento;
     private String tanMotivo;
     private char tanEstaactivo;
     private String tanCreado;
     private Date tanFechaCreacion;
     private String tanActualizado;
     private Date tanFechaActualizacion;

    public SgpTesisAnulacion() {
    }

	
    public SgpTesisAnulacion(int tanId, SgpTesis sgpTesis, Date tanFechaAprobacion, String tanNroDocumento, char tanEstaactivo, String tanCreado, Date tanFechaCreacion) {
        this.tanId = tanId;
        this.sgpTesis = sgpTesis;
        this.tanFechaAprobacion = tanFechaAprobacion;
        this.tanNroDocumento = tanNroDocumento;
        this.tanEstaactivo = tanEstaactivo;
        this.tanCreado = tanCreado;
        this.tanFechaCreacion = tanFechaCreacion;
    }
    public SgpTesisAnulacion(int tanId, SgpTesis sgpTesis, Date tanFechaAprobacion, String tanNroDocumento, String tanMotivo, char tanEstaactivo, String tanCreado, Date tanFechaCreacion, String tanActualizado, Date tanFechaActualizacion) {
       this.tanId = tanId;
       this.sgpTesis = sgpTesis;
       this.tanFechaAprobacion = tanFechaAprobacion;
       this.tanNroDocumento = tanNroDocumento;
       this.tanMotivo = tanMotivo;
       this.tanEstaactivo = tanEstaactivo;
       this.tanCreado = tanCreado;
       this.tanFechaCreacion = tanFechaCreacion;
       this.tanActualizado = tanActualizado;
       this.tanFechaActualizacion = tanFechaActualizacion;
    }
   
    public int getTanId() {
        return this.tanId;
    }
    
    public void setTanId(int tanId) {
        this.tanId = tanId;
    }
    public SgpTesis getSgpTesis() {
        return this.sgpTesis;
    }
    
    public void setSgpTesis(SgpTesis sgpTesis) {
        this.sgpTesis = sgpTesis;
    }
    public Date getTanFechaAprobacion() {
        return this.tanFechaAprobacion;
    }
    
    public void setTanFechaAprobacion(Date tanFechaAprobacion) {
        this.tanFechaAprobacion = tanFechaAprobacion;
    }
    public String getTanNroDocumento() {
        return this.tanNroDocumento;
    }
    
    public void setTanNroDocumento(String tanNroDocumento) {
        this.tanNroDocumento = tanNroDocumento;
    }
    public String getTanMotivo() {
        return this.tanMotivo;
    }
    
    public void setTanMotivo(String tanMotivo) {
        this.tanMotivo = tanMotivo;
    }
    public char getTanEstaactivo() {
        return this.tanEstaactivo;
    }
    
    public void setTanEstaactivo(char tanEstaactivo) {
        this.tanEstaactivo = tanEstaactivo;
    }
    public String getTanCreado() {
        return this.tanCreado;
    }
    
    public void setTanCreado(String tanCreado) {
        this.tanCreado = tanCreado;
    }
    public Date getTanFechaCreacion() {
        return this.tanFechaCreacion;
    }
    
    public void setTanFechaCreacion(Date tanFechaCreacion) {
        this.tanFechaCreacion = tanFechaCreacion;
    }
    public String getTanActualizado() {
        return this.tanActualizado;
    }
    
    public void setTanActualizado(String tanActualizado) {
        this.tanActualizado = tanActualizado;
    }
    public Date getTanFechaActualizacion() {
        return this.tanFechaActualizacion;
    }
    
    public void setTanFechaActualizacion(Date tanFechaActualizacion) {
        this.tanFechaActualizacion = tanFechaActualizacion;
    }




}


