package datos.pojos.sgap;
// Generated 04/04/2014 10:30:05 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpTesisTribunal generated by hbm2java
 */
public class SgpTesisTribunal  implements java.io.Serializable {


     private SgpTesisTribunalId id;
     private SgpTesis sgpTesis;
     private char tetEstaactivo;
     private String tetCreado;
     private Date tetFechaCreacion;
     private String tetActualizado;
     private Date tetFechaActualizacion;

    public SgpTesisTribunal() {
    }

	
    public SgpTesisTribunal(SgpTesisTribunalId id, SgpTesis sgpTesis, char tetEstaactivo, String tetCreado, Date tetFechaCreacion) {
        this.id = id;
        this.sgpTesis = sgpTesis;
        this.tetEstaactivo = tetEstaactivo;
        this.tetCreado = tetCreado;
        this.tetFechaCreacion = tetFechaCreacion;
    }
    public SgpTesisTribunal(SgpTesisTribunalId id, SgpTesis sgpTesis, char tetEstaactivo, String tetCreado, Date tetFechaCreacion, String tetActualizado, Date tetFechaActualizacion) {
       this.id = id;
       this.sgpTesis = sgpTesis;
       this.tetEstaactivo = tetEstaactivo;
       this.tetCreado = tetCreado;
       this.tetFechaCreacion = tetFechaCreacion;
       this.tetActualizado = tetActualizado;
       this.tetFechaActualizacion = tetFechaActualizacion;
    }
   
    public SgpTesisTribunalId getId() {
        return this.id;
    }
    
    public void setId(SgpTesisTribunalId id) {
        this.id = id;
    }
    public SgpTesis getSgpTesis() {
        return this.sgpTesis;
    }
    
    public void setSgpTesis(SgpTesis sgpTesis) {
        this.sgpTesis = sgpTesis;
    }
    public char getTetEstaactivo() {
        return this.tetEstaactivo;
    }
    
    public void setTetEstaactivo(char tetEstaactivo) {
        this.tetEstaactivo = tetEstaactivo;
    }
    public String getTetCreado() {
        return this.tetCreado;
    }
    
    public void setTetCreado(String tetCreado) {
        this.tetCreado = tetCreado;
    }
    public Date getTetFechaCreacion() {
        return this.tetFechaCreacion;
    }
    
    public void setTetFechaCreacion(Date tetFechaCreacion) {
        this.tetFechaCreacion = tetFechaCreacion;
    }
    public String getTetActualizado() {
        return this.tetActualizado;
    }
    
    public void setTetActualizado(String tetActualizado) {
        this.tetActualizado = tetActualizado;
    }
    public Date getTetFechaActualizacion() {
        return this.tetFechaActualizacion;
    }
    
    public void setTetFechaActualizacion(Date tetFechaActualizacion) {
        this.tetFechaActualizacion = tetFechaActualizacion;
    }




}


