package datos.pojos.sgap;
// Generated 12/12/2013 10:26:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpTiposProcesos generated by hbm2java
 */
public class SgpTiposProcesos  implements java.io.Serializable {


     private short tipId;
     private String tipNombre;
     private short tipOrden;
     private char tipEstaactivo;
     private String tipCreado;
     private Date tipFechaCreacion;
     private String tipActualizado;
     private Date tipFechaActualizacion;
     private Set sgpDocumentosAutorizacions = new HashSet(0);

    public SgpTiposProcesos() {
    }

	
    public SgpTiposProcesos(short tipId, String tipNombre, short tipOrden, char tipEstaactivo, String tipCreado, Date tipFechaCreacion) {
        this.tipId = tipId;
        this.tipNombre = tipNombre;
        this.tipOrden = tipOrden;
        this.tipEstaactivo = tipEstaactivo;
        this.tipCreado = tipCreado;
        this.tipFechaCreacion = tipFechaCreacion;
    }
    public SgpTiposProcesos(short tipId, String tipNombre, short tipOrden, char tipEstaactivo, String tipCreado, Date tipFechaCreacion, String tipActualizado, Date tipFechaActualizacion, Set sgpDocumentosAutorizacions) {
       this.tipId = tipId;
       this.tipNombre = tipNombre;
       this.tipOrden = tipOrden;
       this.tipEstaactivo = tipEstaactivo;
       this.tipCreado = tipCreado;
       this.tipFechaCreacion = tipFechaCreacion;
       this.tipActualizado = tipActualizado;
       this.tipFechaActualizacion = tipFechaActualizacion;
       this.sgpDocumentosAutorizacions = sgpDocumentosAutorizacions;
    }
   
    public short getTipId() {
        return this.tipId;
    }
    
    public void setTipId(short tipId) {
        this.tipId = tipId;
    }
    public String getTipNombre() {
        return this.tipNombre;
    }
    
    public void setTipNombre(String tipNombre) {
        this.tipNombre = tipNombre;
    }
    public short getTipOrden() {
        return this.tipOrden;
    }
    
    public void setTipOrden(short tipOrden) {
        this.tipOrden = tipOrden;
    }
    public char getTipEstaactivo() {
        return this.tipEstaactivo;
    }
    
    public void setTipEstaactivo(char tipEstaactivo) {
        this.tipEstaactivo = tipEstaactivo;
    }
    public String getTipCreado() {
        return this.tipCreado;
    }
    
    public void setTipCreado(String tipCreado) {
        this.tipCreado = tipCreado;
    }
    public Date getTipFechaCreacion() {
        return this.tipFechaCreacion;
    }
    
    public void setTipFechaCreacion(Date tipFechaCreacion) {
        this.tipFechaCreacion = tipFechaCreacion;
    }
    public String getTipActualizado() {
        return this.tipActualizado;
    }
    
    public void setTipActualizado(String tipActualizado) {
        this.tipActualizado = tipActualizado;
    }
    public Date getTipFechaActualizacion() {
        return this.tipFechaActualizacion;
    }
    
    public void setTipFechaActualizacion(Date tipFechaActualizacion) {
        this.tipFechaActualizacion = tipFechaActualizacion;
    }
    public Set getSgpDocumentosAutorizacions() {
        return this.sgpDocumentosAutorizacions;
    }
    
    public void setSgpDocumentosAutorizacions(Set sgpDocumentosAutorizacions) {
        this.sgpDocumentosAutorizacions = sgpDocumentosAutorizacions;
    }




}


