package datos.pojos.sgap;
// Generated 04/04/2014 10:30:05 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpTesisEstudianteId generated by hbm2java
 */
public class SgpTesisEstudianteId  implements java.io.Serializable {


     private int teeTesisId;
     private String teePersonaId;

    public SgpTesisEstudianteId() {
    }

    public SgpTesisEstudianteId(int teeTesisId, String teePersonaId) {
       this.teeTesisId = teeTesisId;
       this.teePersonaId = teePersonaId;
    }
   
    public int getTeeTesisId() {
        return this.teeTesisId;
    }
    
    public void setTeeTesisId(int teeTesisId) {
        this.teeTesisId = teeTesisId;
    }
    public String getTeePersonaId() {
        return this.teePersonaId;
    }
    
    public void setTeePersonaId(String teePersonaId) {
        this.teePersonaId = teePersonaId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpTesisEstudianteId) ) return false;
		 SgpTesisEstudianteId castOther = ( SgpTesisEstudianteId ) other; 
         
		 return (this.getTeeTesisId()==castOther.getTeeTesisId())
 && ( (this.getTeePersonaId()==castOther.getTeePersonaId()) || ( this.getTeePersonaId()!=null && castOther.getTeePersonaId()!=null && this.getTeePersonaId().equals(castOther.getTeePersonaId()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTeeTesisId();
         result = 37 * result + ( getTeePersonaId() == null ? 0 : this.getTeePersonaId().hashCode() );
         return result;
   }   


}


