package datos.pojos.sgap;
// Generated 04/04/2014 10:30:05 AM by Hibernate Tools 3.2.1.GA



/**
 * SgpTesisTribunalId generated by hbm2java
 */
public class SgpTesisTribunalId  implements java.io.Serializable {


     private short tetId;
     private String tetPersonaId;
     private int tetTesisId;

    public SgpTesisTribunalId() {
    }

    public SgpTesisTribunalId(short tetId, String tetPersonaId, int tetTesisId) {
       this.tetId = tetId;
       this.tetPersonaId = tetPersonaId;
       this.tetTesisId = tetTesisId;
    }
   
    public short getTetId() {
        return this.tetId;
    }
    
    public void setTetId(short tetId) {
        this.tetId = tetId;
    }
    public String getTetPersonaId() {
        return this.tetPersonaId;
    }
    
    public void setTetPersonaId(String tetPersonaId) {
        this.tetPersonaId = tetPersonaId;
    }
    public int getTetTesisId() {
        return this.tetTesisId;
    }
    
    public void setTetTesisId(int tetTesisId) {
        this.tetTesisId = tetTesisId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SgpTesisTribunalId) ) return false;
		 SgpTesisTribunalId castOther = ( SgpTesisTribunalId ) other; 
         
		 return (this.getTetId()==castOther.getTetId())
 && ( (this.getTetPersonaId()==castOther.getTetPersonaId()) || ( this.getTetPersonaId()!=null && castOther.getTetPersonaId()!=null && this.getTetPersonaId().equals(castOther.getTetPersonaId()) ) )
 && (this.getTetTesisId()==castOther.getTetTesisId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getTetId();
         result = 37 * result + ( getTetPersonaId() == null ? 0 : this.getTetPersonaId().hashCode() );
         result = 37 * result + this.getTetTesisId();
         return result;
   }   


}


