package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * SgpTiposDuracion generated by hbm2java
 */
public class SgpTiposDuracion  implements java.io.Serializable {


     private byte id;
     private String nombre;
     private String nombrePlural;
     private String abreviatura;
     private char estaactivo;
     private String creado;
     private Date fechaCreacion;
     private String actualizado;
     private Date fehaActualizacion;

    public SgpTiposDuracion() {
    }

	
    public SgpTiposDuracion(byte id, String nombre, String nombrePlural, char estaactivo, String creado, Date fechaCreacion) {
        this.id = id;
        this.nombre = nombre;
        this.nombrePlural = nombrePlural;
        this.estaactivo = estaactivo;
        this.creado = creado;
        this.fechaCreacion = fechaCreacion;
    }
    public SgpTiposDuracion(byte id, String nombre, String nombrePlural, String abreviatura, char estaactivo, String creado, Date fechaCreacion, String actualizado, Date fehaActualizacion) {
       this.id = id;
       this.nombre = nombre;
       this.nombrePlural = nombrePlural;
       this.abreviatura = abreviatura;
       this.estaactivo = estaactivo;
       this.creado = creado;
       this.fechaCreacion = fechaCreacion;
       this.actualizado = actualizado;
       this.fehaActualizacion = fehaActualizacion;
    }
   
    public byte getId() {
        return this.id;
    }
    
    public void setId(byte id) {
        this.id = id;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getNombrePlural() {
        return this.nombrePlural;
    }
    
    public void setNombrePlural(String nombrePlural) {
        this.nombrePlural = nombrePlural;
    }
    public String getAbreviatura() {
        return this.abreviatura;
    }
    
    public void setAbreviatura(String abreviatura) {
        this.abreviatura = abreviatura;
    }
    public char getEstaactivo() {
        return this.estaactivo;
    }
    
    public void setEstaactivo(char estaactivo) {
        this.estaactivo = estaactivo;
    }
    public String getCreado() {
        return this.creado;
    }
    
    public void setCreado(String creado) {
        this.creado = creado;
    }
    public Date getFechaCreacion() {
        return this.fechaCreacion;
    }
    
    public void setFechaCreacion(Date fechaCreacion) {
        this.fechaCreacion = fechaCreacion;
    }
    public String getActualizado() {
        return this.actualizado;
    }
    
    public void setActualizado(String actualizado) {
        this.actualizado = actualizado;
    }
    public Date getFehaActualizacion() {
        return this.fehaActualizacion;
    }
    
    public void setFehaActualizacion(Date fehaActualizacion) {
        this.fehaActualizacion = fehaActualizacion;
    }




}


