package datos.pojos.sgap;
// Generated 16/12/2013 09:50:34 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpUnidadesCabecera generated by hbm2java
 */
public class SgpUnidadesCabecera  implements java.io.Serializable {


     private int uncId;
     private String uncDescripcion;
     private String uncTipo;
     private char uncEnvigencia;
     private char uncEstaactivo;
     private String uncCreado;
     private Date uncFechaCreacion;
     private String uncActualizado;
     private Date uncFechaActualizacion;
     private Set sgpUnidadesOrganizacions = new HashSet(0);

    public SgpUnidadesCabecera() {
    }

	
    public SgpUnidadesCabecera(int uncId, String uncDescripcion, String uncTipo, char uncEnvigencia, char uncEstaactivo, String uncCreado, Date uncFechaCreacion) {
        this.uncId = uncId;
        this.uncDescripcion = uncDescripcion;
        this.uncTipo = uncTipo;
        this.uncEnvigencia = uncEnvigencia;
        this.uncEstaactivo = uncEstaactivo;
        this.uncCreado = uncCreado;
        this.uncFechaCreacion = uncFechaCreacion;
    }
    public SgpUnidadesCabecera(int uncId, String uncDescripcion, String uncTipo, char uncEnvigencia, char uncEstaactivo, String uncCreado, Date uncFechaCreacion, String uncActualizado, Date uncFechaActualizacion, Set sgpUnidadesOrganizacions) {
       this.uncId = uncId;
       this.uncDescripcion = uncDescripcion;
       this.uncTipo = uncTipo;
       this.uncEnvigencia = uncEnvigencia;
       this.uncEstaactivo = uncEstaactivo;
       this.uncCreado = uncCreado;
       this.uncFechaCreacion = uncFechaCreacion;
       this.uncActualizado = uncActualizado;
       this.uncFechaActualizacion = uncFechaActualizacion;
       this.sgpUnidadesOrganizacions = sgpUnidadesOrganizacions;
    }
   
    public int getUncId() {
        return this.uncId;
    }
    
    public void setUncId(int uncId) {
        this.uncId = uncId;
    }
    public String getUncDescripcion() {
        return this.uncDescripcion;
    }
    
    public void setUncDescripcion(String uncDescripcion) {
        this.uncDescripcion = uncDescripcion;
    }
    public String getUncTipo() {
        return this.uncTipo;
    }
    
    public void setUncTipo(String uncTipo) {
        this.uncTipo = uncTipo;
    }
    public char getUncEnvigencia() {
        return this.uncEnvigencia;
    }
    
    public void setUncEnvigencia(char uncEnvigencia) {
        this.uncEnvigencia = uncEnvigencia;
    }
    public char getUncEstaactivo() {
        return this.uncEstaactivo;
    }
    
    public void setUncEstaactivo(char uncEstaactivo) {
        this.uncEstaactivo = uncEstaactivo;
    }
    public String getUncCreado() {
        return this.uncCreado;
    }
    
    public void setUncCreado(String uncCreado) {
        this.uncCreado = uncCreado;
    }
    public Date getUncFechaCreacion() {
        return this.uncFechaCreacion;
    }
    
    public void setUncFechaCreacion(Date uncFechaCreacion) {
        this.uncFechaCreacion = uncFechaCreacion;
    }
    public String getUncActualizado() {
        return this.uncActualizado;
    }
    
    public void setUncActualizado(String uncActualizado) {
        this.uncActualizado = uncActualizado;
    }
    public Date getUncFechaActualizacion() {
        return this.uncFechaActualizacion;
    }
    
    public void setUncFechaActualizacion(Date uncFechaActualizacion) {
        this.uncFechaActualizacion = uncFechaActualizacion;
    }
    public Set getSgpUnidadesOrganizacions() {
        return this.sgpUnidadesOrganizacions;
    }
    
    public void setSgpUnidadesOrganizacions(Set sgpUnidadesOrganizacions) {
        this.sgpUnidadesOrganizacions = sgpUnidadesOrganizacions;
    }




}


