package datos.pojos.sgap;
// Generated 16/12/2013 07:48:02 AM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * SgpUnidadesOrganizacion generated by hbm2java
 */
public class SgpUnidadesOrganizacion implements java.io.Serializable {

    private int unoId;
    private SgpUnidadesCabecera sgpUnidadesCabecera;
    private String unoNombre;
    private String unoNombreCorto;
    private String unoColor;
    private char unoEstaactivo;
    private String unoCreado;
    private Date unoFechaCreacion;
    private String unoActualizado;
    private Date unoFechaActualizacion;
    private Set sgpAsignaturasMallases = new HashSet(0);
    private Set sgpUnidadesMallas = new HashSet(0);

    public SgpUnidadesOrganizacion() {
    }

    public SgpUnidadesOrganizacion(int unoId) {
        this.unoId = unoId;
    }

    
    public SgpUnidadesOrganizacion(int unoId, String unoNombre, String unoNombreCorto, String unoColor, char unoEstaactivo, String unoCreado, Date unoFechaCreacion) {
        this.unoId = unoId;
        this.unoNombre = unoNombre;
        this.unoNombreCorto = unoNombreCorto;
        this.unoColor = unoColor;
        this.unoEstaactivo = unoEstaactivo;
        this.unoCreado = unoCreado;
        this.unoFechaCreacion = unoFechaCreacion;
    }

    public SgpUnidadesOrganizacion(int unoId, String unoNombre, String unoNombreCorto, String unoColor, char unoEstaactivo, String unoCreado, Date unoFechaCreacion, String unoActualizado, Date unoFechaActualizacion, Set sgpAsignaturasMallases) {
        this.unoId = unoId;
        this.unoNombre = unoNombre;
        this.unoNombreCorto = unoNombreCorto;
        this.unoColor = unoColor;
        this.unoEstaactivo = unoEstaactivo;
        this.unoCreado = unoCreado;
        this.unoFechaCreacion = unoFechaCreacion;
        this.unoActualizado = unoActualizado;
        this.unoFechaActualizacion = unoFechaActualizacion;
        this.sgpAsignaturasMallases = sgpAsignaturasMallases;
    }

    public int getUnoId() {
        return this.unoId;
    }

    public void setUnoId(int unoId) {
        this.unoId = unoId;
    }

    public String getUnoNombre() {
        return this.unoNombre;
    }

    public void setUnoNombre(String unoNombre) {
        this.unoNombre = unoNombre;
    }

    public String getUnoNombreCorto() {
        return this.unoNombreCorto;
    }

    public void setUnoNombreCorto(String unoNombreCorto) {
        this.unoNombreCorto = unoNombreCorto;
    }

    public String getUnoColor() {
        return this.unoColor;
    }

    public void setUnoColor(String unoColor) {
        this.unoColor = unoColor;
    }

    public char getUnoEstaactivo() {
        return this.unoEstaactivo;
    }

    public void setUnoEstaactivo(char unoEstaactivo) {
        this.unoEstaactivo = unoEstaactivo;
    }

    public String getUnoCreado() {
        return this.unoCreado;
    }

    public void setUnoCreado(String unoCreado) {
        this.unoCreado = unoCreado;
    }

    public Date getUnoFechaCreacion() {
        return this.unoFechaCreacion;
    }

    public void setUnoFechaCreacion(Date unoFechaCreacion) {
        this.unoFechaCreacion = unoFechaCreacion;
    }

    public String getUnoActualizado() {
        return this.unoActualizado;
    }

    public void setUnoActualizado(String unoActualizado) {
        this.unoActualizado = unoActualizado;
    }

    public Date getUnoFechaActualizacion() {
        return this.unoFechaActualizacion;
    }

    public void setUnoFechaActualizacion(Date unoFechaActualizacion) {
        this.unoFechaActualizacion = unoFechaActualizacion;
    }

    public Set getSgpAsignaturasMallases() {
        return this.sgpAsignaturasMallases;
    }

    public void setSgpAsignaturasMallases(Set sgpAsignaturasMallases) {
        this.sgpAsignaturasMallases = sgpAsignaturasMallases;
    }

    public Set getSgpUnidadesMallas() {
        return sgpUnidadesMallas;
    }

    public void setSgpUnidadesMallas(Set sgpUnidadesMallas) {
        this.sgpUnidadesMallas = sgpUnidadesMallas;
    }

    public SgpUnidadesCabecera getSgpUnidadesCabecera() {
        return sgpUnidadesCabecera;
    }

    public void setSgpUnidadesCabecera(SgpUnidadesCabecera sgpUnidadesCabecera) {
        this.sgpUnidadesCabecera = sgpUnidadesCabecera;
    }
    
}
