package datos.pojos.sgap;
// Generated 23/04/2012 09:23:45 AM by Hibernate Tools 3.2.1.GA


/**
 * VstAccesosPath generated by hbm2java
 */
public class VstAccesosPath  implements java.io.Serializable {
     
    private VstAccesosPathId id;
    private String dependencia;    
    private String curso;
    private String unidadAcademicaId;
    private String unidadAcademica;
    private String path;
    
    public VstAccesosPath() {
    }    

    public VstAccesosPathId getId() {
        return id;
    }

    public void setId(VstAccesosPathId id) {
        this.id = id;
    }
       
    public String getDependencia() {
        return dependencia;
    }

    public void setDependencia(String dependencia) {
        this.dependencia = dependencia;
    }

    public String getCurso() {
        return curso;
    }

    public void setCurso(String curso) {
        this.curso = curso;
    }

    public String getUnidadAcademicaId() {
        return unidadAcademicaId;
    }

    public void setUnidadAcademicaId(String unidadAcademicaId) {
        this.unidadAcademicaId = unidadAcademicaId;
    }

    public String getUnidadAcademica() {
        return unidadAcademica;
    }

    public void setUnidadAcademica(String unidadAcademica) {
        this.unidadAcademica = unidadAcademica;
    }

    public String getPath() {
        return path;
    }

    public void setPath(String path) {
        this.path = path;
    }
}


